# frozen_string_literal: true

# Disarm git's BACKGROUND MAINTENANCE for every test process, so a throwaway
# repo cannot race its own teardown.
#
# THE FLAKE THIS EXISTS TO KILL. A test creates a repo inside `Dir.mktmpdir`,
# git decides mid-run that the repo is due for housekeeping, and the `ensure`
# block deletes the directory out from under it:
#
#     Errno::ENOENT: No such file or directory @ apply2files
#       - <tmpdir>/.git/objects/maintenance.lock
#
# It has reddened CI at least four times (2026-08-19, -08-20 twice — once on a
# `rails` shard on `accepted` — and 2026-08-30 on CertRootGuardTest). Nothing is
# wrong with the tests. It is a race between git's housekeeping and the tmpdir's
# teardown, and it fires in a DIFFERENT file each time.
#
# WHY IT IS WORSE THAN AN ORDINARY FLAKE: the error names git internals rather
# than the test's subject, so the natural reading is "something is wrong with my
# diff" and the natural response is a re-run, which usually passes. A reviewer
# looking at a green re-run cannot tell this from a real intermittent failure.
# It also costs a full CI cycle, and `--failed` does NOT clear it when a receipt
# guard re-reads attempt 1's artifacts.
#
# WHY A PLUGIN, AND NOT test_helper.rb. `test_helper` is NOT loaded for bare
# minitest files: `Rails::Command::TestCommand#perform` only puts `test/` on
# $LOAD_PATH, and `Rails::TestUnit::Runner.load_tests` does a plain
# `require abs_path` per file. Measured — a bare `test/lib/*_test.rb` run through
# `bin/rails test` reports `test_helper_loaded=false`. The support files are
# opt-in too: only 68 of 176 bare files require `session_env`, and four of the
# files that shell `git init` are not among them.
#
# Minitest discovers plugins by scanning $LOAD_PATH for `minitest/*_plugin.rb`
# (`Minitest.load_plugins` -> `Gem.find_files`), and `Minitest.run` calls
# `load_plugins` BEFORE `process_args` — which is what triggers railties'
# `load_tests`. So this module body executes before a single test file is
# required, on every automated path: `bin/rails test`, `rake test` (which shells
# back to it), `bin/fast-check`, `bin/full-suite-check`, `bin/ci-shard`,
# `bin/agent-worktree test`, and the release gate.
#
# ⚠️ TWO LIMITS, both measured, both worth knowing before you trust this:
#
#   1. THE `minitest (~> 5.25)` PIN IS LOAD-BEARING. minitest 5.27 calls
#      `load_plugins` from `Minitest.run`; minitest 6 REMOVED that call and
#      documents it as "optional, called by user". If that pin ever moves, this
#      file stops loading and the flake returns silently. `bin/ci-shard` already
#      depends on the same mechanism for its receipt and aborts when it is
#      missing, so the two fail together rather than one masking the other.
#      `MT_NO_PLUGINS=1` and `--no-plugins` also disable discovery.
#
#   2. A NON-BUNDLER HAND RUN BYPASSES IT: `ruby -Itest test/lib/x_test.rb`
#      resolves minitest 6 and never loads plugins. 120 test files still carry
#      that recipe in their headers. `bundle exec ruby -Itest ...` is fine, and
#      no automated entry point is affected.
#
# WHY GIT_CONFIG_SYSTEM RATHER THAN THE NUMBERED SLOTS. `GIT_CONFIG_COUNT` /
# `GIT_CONFIG_KEY_n` are ALREADY USED as a child-env overlay by
# test/integration/credential_session_lifecycle_test.rb, which sets COUNT=2 for
# its spawn. A process-wide numbered scheme would be replaced wholesale by that
# hash (its COUNT=2 means git reads only slots 0-1), and renumbering collides the
# other way. `GIT_CONFIG_SYSTEM` has zero other uses in bin/, lib/, config/ or
# .github/, and system config is the lowest-precedence layer — so a repo-local
# `git config` in a fixture still wins, and nothing a test deliberately sets is
# masked.
#
# PLAIN ASSIGNMENT, NOT `||=`, and an explicit opt-out — the shape
# test/support/outbound_seams.rb uses and for the same stated reason: `||=`
# keeps whatever the shell exported, which is wrong when the AMBIENT VALUE IS
# THE HAZARD. `GIT_ISOLATION=off` (or 0/false/no) disables this deliberately.
module GitIsolationPlugin
  OPT_OUT = %w[0 false no off].freeze

  module_function

  def armed?
    !OPT_OUT.include?(ENV.fetch("GIT_ISOLATION", "").to_s.strip.downcase)
  end

  # A real file on disk, because git reads GIT_CONFIG_SYSTEM as a PATH. Written
  # once per process into the system temp dir; `Tempfile` would be reaped by its
  # finalizer while child processes still need the path.
  def config_path
    @config_path ||= begin
      path = File.join(Dir.tmpdir, "mcritchie-git-isolation-#{Process.pid}.gitconfig")
      File.write(path, <<~CONFIG)
        # Generated by test/minitest/git_isolation_plugin.rb — see that file.
        [gc]
        \tauto = 0
        [maintenance]
        \tauto = false
      CONFIG
      path
    end
  end

  def arm!
    ENV["GIT_CONFIG_SYSTEM"] = config_path
  end
end

require "tmpdir"
GitIsolationPlugin.arm! if GitIsolationPlugin.armed?

# Minitest requires a `plugin_<name>_init` method to consider a file a plugin.
# Ours needs no per-run behaviour — the arming above already happened at require
# time, which is EARLIER than init and therefore earlier than any test file.
module Minitest
  def self.plugin_git_isolation_init(_options); end
end
