# frozen_string_literal: true

require "fileutils"
require "open3"
require "tmpdir"
require "yaml"

# The migration baseline: db/migrate holds one create migration per table, so a new
# machine reads each model as it is.
#
#   Generator  writes the baseline from a schema.rb (bin/db-baseline).
#   Marker     records the baseline's versions on a database that already holds the
#              tables, so db:migrate finds nothing to run there (db:baseline:mark).
#   CatchUp    brings a database that stopped partway through the retired ledger to
#              that ledger's head (db:baseline:catch_up).
#
# Procedure: docs/agents/modules/backend-discipline.md, "The Migration Baseline"
module DbBaseline
  # Every baseline version starts with this date, so it sorts before any other migration.
  PREFIX = "20260101"
  RECORD = "db/baseline.yml"
  VIEWS_DIR = "db/views"
  HEADER = "# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here."

  # Native migrations held under the name an engine will ship, ahead of the engine.
  HELD_NAMES = %w[add_last_name_and_newsletter_columns].freeze

  class Error < StandardError; end

  module_function

  def baseline_file?(basename)
    basename.start_with?(PREFIX)
  end

  # An installed engine migration carries its engine's scope: <version>_<name>.<scope>.rb
  def engine_file?(basename)
    basename.match?(/\A\d+_\w+\.\w+\.rb\z/)
  end

  def version_of(basename)
    basename[/\A\d+/].to_s
  end

  # The columns a create_table block names, in a schema dump or a baseline migration.
  def columns_in(text)
    text.scan(/^\s+t\.(\w+) "(\w+)"/).reject { |type, _| %w[index check_constraint].include?(type) }.map(&:last)
  end

  # Compares a schema dump taken from another database with the committed baseline,
  # without a connection. short: tables that lack baseline columns. absent: baseline
  # tables the dump does not hold. behind: the dump predates the retired ledger's head.
  Comparison = Struct.new(:version, :short, :absent, :behind, keyword_init: true)

  def compare(schema_text, root:)
    schema = Schema.new(schema_text)
    held = schema.tables.to_h { |table| [table.name, columns_in(table.block.join("\n"))] }
    tables = Marker.new(connection: nil, migrate_dir: File.join(root.to_s, "db/migrate")).entries.select { |entry| entry.kind == :table }
    present, absent = tables.partition { |entry| held.key?(entry.name) }
    short = present.filter_map do |entry|
      missing = entry.columns - held.fetch(entry.name)
      "#{entry.name} lacks #{missing.join(', ')}" if missing.any?
    end
    record = File.join(root.to_s, RECORD)
    through = File.exist?(record) ? YAML.load_file(record).fetch("retired_through") : "0"
    Comparison.new(version: schema.version, short: short, absent: absent.map(&:name), behind: schema.version < through)
  end

  # The name an engine's install step compares: no version, no scope.
  def bare_name(basename)
    basename.sub(/\A\d+_/, "").sub(/\..*\z/, "")
  end

  # Reads a schema.rb as text. Fails on a statement it does not know.
  class Schema
    Table = Struct.new(:name, :block, keyword_init: true)
    ForeignKey = Struct.new(:from, :to, :line, keyword_init: true)

    attr_reader :version, :rails, :extensions, :tables, :foreign_keys

    def initialize(text)
      @extensions = []
      @tables = []
      @foreign_keys = []
      parse(text)
    end

    private

    def parse(text)
      lines = text.lines.map(&:chomp)
      head = lines.find { |line| line.start_with?("ActiveRecord::Schema") }
      match = head&.match(/Schema\[(?<rails>[\d.]+)\]\.define\(version: (?<version>[\d_]+)\)/)
      raise Error, "no ActiveRecord::Schema header found" unless match

      @rails = match[:rails]
      @version = match[:version].delete("_")
      body = lines[(lines.index(head) + 1)..]
      until body.empty?
        line = body.shift
        break if line == "end"
        next if line.strip.empty? || line.start_with?("  #")

        if line.start_with?("  enable_extension ")
          @extensions << line.strip
        elsif (table = line.match(/\A  create_table "(\w+)"/))
          block = [line]
          block << body.shift until block.last == "  end" || body.empty?
          @tables << Table.new(name: table[1], block: block)
        elsif (fk = line.match(/\A  add_foreign_key "(\w+)", "(\w+)"/))
          @foreign_keys << ForeignKey.new(from: fk[1], to: fk[2], line: line.strip)
        else
          raise Error, "schema statement the baseline cannot write: #{line.strip}"
        end
      end
    end
  end

  # Writes the baseline into a migrations directory and removes the files it supersedes.
  class Generator
    attr_reader :root, :schema

    # engine_names: the bare name of every migration a loaded engine ships.
    def initialize(root:, schema_text:, engine_names: [], camelize: ->(name) { name.camelize })
      @root = root.to_s
      @schema = Schema.new(schema_text)
      @engine_names = engine_names
      @camelize = camelize
    end

    def migrate_dir = File.join(root, "db/migrate")

    def existing = Dir.children(migrate_dir).grep(/\A\d+_.*\.rb\z/).sort

    # Kept as they are: installed engine migrations, native files that stand in for an
    # engine migration by name, and anything newer than the schema.
    def kept
      existing.select do |file|
        next false if DbBaseline.baseline_file?(file)

        DbBaseline.engine_file?(file) || stand_in?(file) || DbBaseline.version_of(file) > schema.version
      end
    end

    # An engine's install step skips a migration whose name the app already holds. A
    # stand-in named create_<table> is replaced by that table's baseline migration,
    # which carries the same name.
    def stand_in?(file)
      name = DbBaseline.bare_name(file)
      (@engine_names + HELD_NAMES).include?(name) && schema.tables.none? { |table| "create_#{table.name}" == name }
    end

    def retired = existing.reject { |file| DbBaseline.baseline_file?(file) } - kept

    # Tables a kept migration creates with no guard; that migration stays their creator.
    def kept_tables
      names = schema.tables.map(&:name)
      kept.flat_map do |file|
        text = File.read(File.join(migrate_dir, file))
        text.scan(/create_table\s+[:"](\w+)/).flatten.reject { |table| text.match?(/table_exists\?\(:#{table}\)/) }
      end.uniq & names
    end

    def baseline_tables
      skip = kept_tables
      sort(schema.tables.reject { |table| skip.include?(table.name) })
    end

    # name => source for every baseline migration, in run order.
    def migrations
      files = {}
      number = 0
      add = lambda do |name, source|
        number += 1
        files[format("%s%06d_%s.rb", PREFIX, number, name)] = source
      end
      add.call("enable_extensions", extensions_source) if schema.extensions.any?
      tables = baseline_tables
      order = tables.map(&:name)
      tables.each { |table| add.call("create_#{table.name}", table_source(table, keys_for(table, order))) }
      views.each { |name, sql| add.call("create_#{name}_view", view_source(name, sql)) }
      clash = files.keys.map { |file| DbBaseline.bare_name(file) } & kept.map { |file| DbBaseline.bare_name(file) }
      raise Error, "baseline names collide with kept migrations: #{clash.join(', ')}" if clash.any?

      files
    end

    def views
      Dir[File.join(root, VIEWS_DIR, "*.sql")].sort.to_h { |path| [File.basename(path, ".sql"), File.read(path).strip] }
    end

    # Writes the files. `ref` is the commit that still holds the retired ledger.
    def write!(ref:)
      gone = retired
      sources = migrations
      (existing.select { |file| DbBaseline.baseline_file?(file) } + gone).each { |file| FileUtils.rm(File.join(migrate_dir, file)) }
      sources.each { |file, source| File.write(File.join(migrate_dir, file), source) }
      write_record(ref) if gone.any?
      { written: sources.keys, retired: gone, kept: kept }
    end

    private

    def write_record(ref)
      body = { "retired_ref" => ref, "retired_through" => schema.version }
      File.write(File.join(root, RECORD), "# Written by bin/db-baseline: the commit that last held the retired ledger.\n#{body.to_yaml}")
    end

    # A table follows every table it points at, so its foreign keys sit in its own
    # migration. Where tables point at each other, the one most pointed at goes first
    # and its key waits in the migration of the table it points at.
    def sort(tables)
      names = tables.map(&:name)
      needs = tables.to_h do |table|
        targets = schema.foreign_keys.select { |fk| fk.from == table.name }.map(&:to).uniq - [table.name]
        outside = targets - names
        raise Error, "#{table.name} has a foreign key to #{outside.join(', ')}, which a kept migration creates later" if outside.any?

        [table.name, targets]
      end
      ordered = []
      until needs.empty?
        ready = needs.select { |_, targets| (targets - ordered).empty? }.keys.min
        ready ||= needs.keys.min_by { |name| [-needs.values.count { |targets| targets.include?(name) }, name] }
        ordered << ready
        needs.delete(ready)
      end
      ordered.map { |name| tables.find { |table| table.name == name } }
    end

    # The foreign keys a table's migration adds: those between it and tables created before it.
    def keys_for(table, order)
      at = order.index(table.name)
      schema.foreign_keys.select do |fk|
        from = order.index(fk.from)
        to = order.index(fk.to)
        from && to && [from, to].max == at
      end
    end

    def class_line(name) = "class #{@camelize.call(name)} < ActiveRecord::Migration[#{schema.rails}]"

    def extensions_source
      <<~RUBY
        #{HEADER}
        #{class_line('enable_extensions')}
          def change
        #{schema.extensions.map { |line| "    #{line}" }.join("\n")}
          end
        end
      RUBY
    end

    def table_source(table, foreign_keys)
      block = table.block.dup
      block[0] = block[0].sub(", force: :cascade", "")
      raise Error, "#{table.name}: a baseline migration never forces a table" if block.join.include?("force:")

      keys = foreign_keys.map { |fk| "    #{fk.line}" }
      body = block.map { |line| "  #{line}" }
      body += ["", *keys] if keys.any?
      "#{HEADER}\n#{class_line("create_#{table.name}")}\n  def change\n#{body.join("\n")}\n  end\nend\n"
    end

    def view_source(name, sql)
      raise Error, "#{VIEWS_DIR}/#{name}.sql must start with CREATE VIEW #{name} AS" unless sql.start_with?("CREATE VIEW #{name} AS")

      <<~RUBY
        #{HEADER}
        # The view's SQL lives in #{VIEWS_DIR}/#{name}.sql. A view never dumps to schema.rb.
        #{class_line("create_#{name}_view")}
          def up
            execute(<<~SQL)
        #{sql.lines.map { |line| "      #{line.chomp}" }.join("\n")}
            SQL
          end

          def down
            execute("DROP VIEW IF EXISTS #{name}")
          end
        end
      RUBY
    end
  end

  # What one baseline migration creates, read from its own source.
  class Entry
    attr_reader :version, :file, :kind, :name, :columns, :base

    def initialize(path)
      @file = File.basename(path)
      @version = DbBaseline.version_of(@file)
      text = File.read(path)
      if (table = text[/create_table "(\w+)"/, 1])
        @kind = :table
        @name = table
        @columns = DbBaseline.columns_in(text)
      elsif (view = text[/CREATE VIEW (\w+) AS/, 1])
        @kind = :view
        @name = view
        @base = text[/\bFROM (\w+)/, 1]
      elsif text.include?("enable_extension")
        @kind = :extensions
        @columns = text.scan(/enable_extension "([\w.]+)"/).flatten
      else
        raise Error, "#{@file} is not a baseline migration this task can read"
      end
    end
  end

  # Records baseline versions where the database already holds what they create.
  # Writes schema_migrations rows and nothing else.
  class Marker
    # recorded: versions already in the ledger. marked: versions this run records.
    # pending: migrations db:migrate will run. short: tables that lack baseline columns.
    Report = Struct.new(:recorded, :marked, :pending, :short, keyword_init: true)

    def initialize(connection:, migrate_dir:)
      @connection = connection
      @migrate_dir = migrate_dir.to_s
    end

    def entries
      Dir[File.join(@migrate_dir, "#{PREFIX}*.rb")].sort.map { |path| Entry.new(path) }
    end

    # Reads only. `short` covers every baseline table the database holds.
    def report
      applied = @connection.table_exists?("schema_migrations") ? @connection.select_values("SELECT version FROM schema_migrations") : []
      all = entries
      done, open = all.partition { |entry| applied.include?(entry.version) }
      present = open.select { |entry| present?(entry) }
      Report.new(recorded: done.map(&:version), marked: present.map(&:version), pending: (open - present).map(&:file),
                 short: (done + present).filter_map { |entry| shortfall(entry) })
    end

    def mark!
      found = report
      raise Error, partway_message(found.short) if found.short.any?

      record(found.marked)
      found
    end

    private

    def present?(entry)
      case entry.kind
      when :table then @connection.table_exists?(entry.name)
      # A database that holds the table and not its view stays as it is.
      when :view then @connection.view_exists?(entry.name) || @connection.table_exists?(entry.base)
      when :extensions then (entry.columns - @connection.extensions).empty?
      end
    end

    def shortfall(entry)
      return unless entry.kind == :table && @connection.table_exists?(entry.name)

      missing = entry.columns - @connection.columns(entry.name).map(&:name)
      "#{entry.name} lacks #{missing.join(', ')}" if missing.any?
    end

    def partway_message(short)
      <<~MSG
        db:baseline:mark changed nothing: this database stopped partway through the retired migrations.
          #{short.join("\n  ")}
        Bring it to the head of the retired ledger, then migrate, with one command:
          bin/rails db:baseline:catch_up
        A database with nothing to keep can be rebuilt instead: bin/rails db:drop db:prepare
      MSG
    end

    def record(versions)
      return if versions.empty?

      @connection.pool.schema_migration.create_table
      values = versions.map { |version| "(#{@connection.quote(version)})" }.join(", ")
      @connection.execute("INSERT INTO schema_migrations (version) VALUES #{values} ON CONFLICT DO NOTHING")
    end
  end

  # Replays the retired ledger out of git, for a database that stopped partway through it.
  class CatchUp
    def initialize(root:, pool:)
      @root = root.to_s
      @pool = pool
    end

    def ref
      path = File.join(@root, RECORD)
      raise Error, "#{RECORD} is missing; there is no retired ledger to replay" unless File.exist?(path)

      YAML.load_file(path).fetch("retired_ref")
    end

    def run!
      Dir.mktmpdir("db-baseline") do |dir|
        files, status = Open3.capture2("git", "-C", @root, "ls-tree", "--name-only", "#{ref}:db/migrate")
        raise Error, "git cannot read db/migrate at #{ref}; fetch the repository's history first" unless status.success?

        files.split("\n").grep(/\A\d+_.*\.rb\z/).each do |file|
          source, = Open3.capture2("git", "-C", @root, "show", "#{ref}:db/migrate/#{file}")
          File.write(File.join(dir, file), source)
        end
        ActiveRecord::MigrationContext.new(dir, @pool.schema_migration, @pool.internal_metadata).migrate
      end
    end
  end
end
