# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateGithubCommitRanges < ActiveRecord::Migration[8.1]
  def change
    create_table "github_commit_ranges" do |t|
      t.datetime "created_at", null: false
      t.string "label", null: false
      t.datetime "updated_at", null: false
      t.date "week_end_date", null: false
      t.date "week_start_date", null: false
      t.index ["week_end_date"], name: "index_github_commit_ranges_on_week_end_date"
      t.index ["week_start_date"], name: "index_github_commit_ranges_on_week_start_date", unique: true
    end
  end
end
