# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreatePffTeamStats < ActiveRecord::Migration[8.1]
  def change
    create_table "pff_team_stats" do |t|
      t.datetime "created_at", null: false
      t.jsonb "data", default: {}, null: false
      t.string "season_slug", null: false
      t.string "slug", null: false
      t.string "stat_type", null: false
      t.string "team_slug", null: false
      t.datetime "updated_at", null: false
      t.index ["data"], name: "index_pff_team_stats_on_data", using: :gin
      t.index ["slug"], name: "index_pff_team_stats_on_slug", unique: true
      t.index ["team_slug", "season_slug", "stat_type"], name: "idx_pff_team_stats_unique", unique: true
    end

    add_foreign_key "pff_team_stats", "seasons", column: "season_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "pff_team_stats", "teams", column: "team_slug", primary_key: "slug", on_update: :cascade
  end
end
