# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateMailboxDrafts < ActiveRecord::Migration[8.1]
  def change
    create_table "mailbox_drafts" do |t|
      t.datetime "created_at", null: false
      t.string "drafted_by", null: false
      t.string "gmail_draft_id", null: false
      t.string "gmail_message_id"
      t.string "gmail_thread_id"
      t.string "mailbox_address", null: false
      t.string "recipients"
      t.string "subject"
      t.datetime "updated_at", null: false
      t.bigint "workspace_mailbox_id", null: false
      t.index ["mailbox_address"], name: "index_mailbox_drafts_on_mailbox_address"
      t.index ["workspace_mailbox_id"], name: "index_mailbox_drafts_on_workspace_mailbox_id"
    end

    add_foreign_key "mailbox_drafts", "workspace_mailboxes"
  end
end
