# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateSkillAssignments < ActiveRecord::Migration[8.1]
  def change
    create_table "skill_assignments" do |t|
      t.string "agent_slug", null: false
      t.datetime "created_at", null: false
      t.integer "proficiency", default: 100
      t.string "skill_slug", null: false
      t.datetime "updated_at", null: false
      t.index ["agent_slug", "skill_slug"], name: "index_skill_assignments_on_agent_slug_and_skill_slug", unique: true
      t.index ["agent_slug"], name: "index_skill_assignments_on_agent_slug"
      t.index ["skill_slug"], name: "index_skill_assignments_on_skill_slug"
    end

    add_foreign_key "skill_assignments", "agents", column: "agent_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "skill_assignments", "skills", column: "skill_slug", primary_key: "slug", on_update: :cascade
  end
end
