# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateContactSubmissions < ActiveRecord::Migration[8.1]
  def change
    create_table "contact_submissions" do |t|
      t.datetime "created_at", null: false
      t.text "disclosure_text", null: false
      t.string "disclosure_version", null: false
      t.string "email", null: false
      t.string "ip_address"
      t.text "message", null: false
      t.string "name", null: false
      t.string "phone"
      t.boolean "sms_care_consent", default: false, null: false
      t.boolean "sms_declined", default: false, null: false
      t.boolean "sms_marketing_consent", default: false, null: false
      t.string "spam_reason"
      t.datetime "updated_at", null: false
      t.text "user_agent"
      t.index "lower((email)::text)", name: "index_contact_submissions_on_lower_email"
      t.index ["created_at"], name: "index_contact_submissions_on_created_at"
    end
  end
end
