# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateSkills < ActiveRecord::Migration[8.1]
  def change
    create_table "skills" do |t|
      t.string "category"
      t.jsonb "config", default: {}
      t.datetime "created_at", null: false
      t.text "description"
      t.string "name", null: false
      t.string "slug", null: false
      t.datetime "updated_at", null: false
      t.index ["category"], name: "index_skills_on_category"
      t.index ["slug"], name: "index_skills_on_slug", unique: true
    end
  end
end
