# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateVideoChunkTakes < ActiveRecord::Migration[8.1]
  def change
    create_table "video_chunk_takes" do |t|
      t.bigint "byte_size", null: false
      t.integer "chunk_ordinal", null: false
      t.datetime "created_at", null: false
      t.datetime "current_since", null: false
      t.integer "end_ms", null: false
      t.string "music_video_slug", null: false
      t.integer "number", null: false
      t.string "object_key", null: false
      t.string "original_filename"
      t.integer "start_ms", null: false
      t.datetime "updated_at", null: false
      t.index ["music_video_slug", "chunk_ordinal", "number"], name: "index_video_chunk_takes_on_video_chunk_and_number", unique: true
      t.index ["object_key"], name: "index_video_chunk_takes_on_object_key", unique: true
    end

    add_foreign_key "video_chunk_takes", "music_videos", column: "music_video_slug", primary_key: "slug", on_update: :cascade
  end
end
