# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateAgents < ActiveRecord::Migration[8.1]
  def change
    create_table "agents" do |t|
      t.string "agent_type"
      t.string "avatar"
      t.jsonb "config", default: {}
      t.datetime "created_at", null: false
      t.text "description"
      t.datetime "last_active_at"
      t.jsonb "metadata", default: {}
      t.string "name", null: false
      t.integer "position", default: 0
      t.string "slug", null: false
      t.string "status", default: "active"
      t.string "title"
      t.datetime "updated_at", null: false
      t.index ["slug"], name: "index_agents_on_slug", unique: true
      t.index ["status"], name: "index_agents_on_status"
    end
  end
end
