# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateActionGrades < ActiveRecord::Migration[8.1]
  def change
    create_table "action_grades" do |t|
      t.bigint "agent_action_id"
      t.bigint "agent_activity_id"
      t.boolean "banked", default: false, null: false
      t.datetime "created_at", null: false
      t.boolean "discarded", default: false, null: false
      t.string "disposition", null: false
      t.string "grader", null: false
      t.text "long_form"
      t.string "slug", null: false
      t.string "source_activity_slug"
      t.datetime "updated_at", null: false
      t.index ["agent_action_id", "grader"], name: "index_action_grades_on_agent_action_id_and_grader", unique: true
      t.index ["agent_action_id"], name: "index_action_grades_on_agent_action_id"
      t.index ["agent_activity_id", "grader"], name: "index_action_grades_on_agent_activity_id_and_grader", unique: true, where: "(agent_activity_id IS NOT NULL)"
      t.index ["agent_activity_id"], name: "index_action_grades_on_agent_activity_id"
      t.index ["banked"], name: "index_action_grades_on_banked"
      t.index ["source_activity_slug"], name: "index_action_grades_on_source_activity_slug", unique: true, where: "(source_activity_slug IS NOT NULL)"
    end

    add_foreign_key "action_grades", "activities", column: "source_activity_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
    add_foreign_key "action_grades", "agent_actions"
    add_foreign_key "action_grades", "agent_activities", on_delete: :nullify
  end
end
