# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateRosterSpots < ActiveRecord::Migration[8.1]
  def change
    create_table "roster_spots" do |t|
      t.datetime "created_at", null: false
      t.integer "depth", default: 1, null: false
      t.string "person_slug", null: false
      t.string "position", null: false
      t.bigint "roster_id", null: false
      t.string "side", null: false
      t.datetime "updated_at", null: false
      t.index ["person_slug"], name: "index_roster_spots_on_person_slug"
      t.index ["roster_id", "position", "depth"], name: "index_roster_spots_on_roster_id_and_position_and_depth", unique: true
      t.index ["roster_id"], name: "index_roster_spots_on_roster_id"
    end

    add_foreign_key "roster_spots", "people", column: "person_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "roster_spots", "rosters"
  end
end
