# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateAgentActions < ActiveRecord::Migration[8.1]
  def change
    create_table "agent_actions" do |t|
      t.string "actor", default: "agent", null: false
      t.bigint "agent_activity_id"
      t.bigint "cache_read_tokens", default: 0
      t.decimal "cost", precision: 10, scale: 4, default: "0.0"
      t.datetime "created_at", null: false
      t.integer "duration_ms"
      t.string "event_slug"
      t.boolean "feedback_anchor", default: false, null: false
      t.string "idempotency_key"
      t.text "input"
      t.text "key_method"
      t.string "key_method_lang"
      t.string "kind", null: false
      t.string "mascot"
      t.string "model"
      t.datetime "occurred_at", null: false
      t.string "outcome", default: "pending", null: false
      t.text "output"
      t.string "result_slug"
      t.integer "seq", default: 0, null: false
      t.string "session_id", null: false
      t.string "source_turn_uuid"
      t.string "stage"
      t.string "summary"
      t.string "task_slug"
      t.bigint "tokens_in", default: 0, null: false
      t.bigint "tokens_out", default: 0, null: false
      t.datetime "updated_at", null: false
      t.index ["agent_activity_id"], name: "index_agent_actions_on_agent_activity_id"
      t.index ["feedback_anchor"], name: "index_agent_actions_on_feedback_anchor"
      t.index ["idempotency_key"], name: "index_agent_actions_on_idempotency_key", unique: true, where: "(idempotency_key IS NOT NULL)"
      t.index ["occurred_at"], name: "index_agent_actions_on_occurred_at"
      t.index ["session_id", "seq"], name: "index_agent_actions_on_session_id_and_seq"
      t.index ["source_turn_uuid"], name: "index_agent_actions_on_source_turn_uuid"
      t.index ["task_slug", "seq"], name: "index_agent_actions_on_task_slug_and_seq"
    end

    add_foreign_key "agent_actions", "agent_activities", on_delete: :nullify
    add_foreign_key "agent_actions", "tasks", column: "task_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
