# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreatePffStats < ActiveRecord::Migration[8.1]
  def change
    create_table "pff_stats" do |t|
      t.string "athlete_slug", null: false
      t.datetime "created_at", null: false
      t.jsonb "data", default: {}, null: false
      t.integer "games_played"
      t.integer "pff_player_id"
      t.string "season_slug", null: false
      t.string "slug", null: false
      t.string "stat_type", null: false
      t.string "team_slug"
      t.datetime "updated_at", null: false
      t.index ["athlete_slug", "season_slug", "stat_type"], name: "idx_pff_stats_unique", unique: true
      t.index ["data"], name: "index_pff_stats_on_data", using: :gin
      t.index ["pff_player_id"], name: "index_pff_stats_on_pff_player_id"
      t.index ["slug"], name: "index_pff_stats_on_slug", unique: true
      t.index ["stat_type"], name: "index_pff_stats_on_stat_type"
    end

    add_foreign_key "pff_stats", "athletes", column: "athlete_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "pff_stats", "seasons", column: "season_slug", primary_key: "slug", on_update: :cascade
  end
end
