# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateTriageFindings < ActiveRecord::Migration[8.1]
  def change
    create_table "triage_findings" do |t|
      t.text "body"
      t.datetime "created_at", null: false
      t.string "prior_art", default: "unknown", null: false
      t.text "prior_art_note"
      t.string "promoted_task_slug"
      t.string "repo"
      t.datetime "resolved_at"
      t.string "slug", null: false
      t.string "source"
      t.string "status", default: "open", null: false
      t.string "title", null: false
      t.datetime "updated_at", null: false
      t.index ["slug"], name: "index_triage_findings_on_slug", unique: true
      t.index ["status"], name: "index_triage_findings_on_status"
    end

    add_foreign_key "triage_findings", "tasks", column: "promoted_task_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
