# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateAppRequests < ActiveRecord::Migration[8.1]
  def change
    create_table "app_requests" do |t|
      t.datetime "created_at", null: false
      t.datetime "discord_notified_at"
      t.text "prompt", null: false
      t.datetime "queued_at"
      t.boolean "showcase", default: false, null: false
      t.string "status", default: "draft", null: false
      t.string "subdomain"
      t.string "task_slug"
      t.string "tier", default: "vibe", null: false
      t.string "token", null: false
      t.datetime "updated_at", null: false
      t.bigint "user_id"
      t.index ["status"], name: "index_app_requests_on_status"
      t.index ["subdomain"], name: "index_app_requests_on_holding_subdomain", unique: true, where: "((subdomain IS NOT NULL) AND ((status)::text = ANY (ARRAY[('queued'::character varying)::text, ('building'::character varying)::text, ('live'::character varying)::text])))"
      t.index ["token"], name: "index_app_requests_on_token", unique: true
      t.index ["user_id"], name: "index_app_requests_on_user_id"
    end

    add_foreign_key "app_requests", "tasks", column: "task_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
    add_foreign_key "app_requests", "users"
  end
end
