# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateBuilders < ActiveRecord::Migration[8.1]
  def change
    create_table "builders" do |t|
      t.boolean "active", default: true, null: false
      t.datetime "created_at", null: false
      t.string "github_avatar_url"
      t.text "github_bio"
      t.string "github_blog"
      t.string "github_company"
      t.string "github_email"
      t.string "github_login", null: false
      t.string "github_name"
      t.string "github_profile_url"
      t.string "github_twitter_username"
      t.boolean "included_in_roster", default: true, null: false
      t.bigint "person_id", null: false
      t.string "primary_language"
      t.jsonb "raw_profile", default: {}, null: false
      t.integer "source_contributions"
      t.string "source_dataset"
      t.integer "source_rank"
      t.string "source_url"
      t.datetime "updated_at", null: false
      t.index ["active", "included_in_roster"], name: "index_builders_on_active_and_included_in_roster"
      t.index ["github_login"], name: "index_builders_on_github_login", unique: true
      t.index ["person_id"], name: "index_builders_on_person_id"
      t.index ["primary_language", "active"], name: "index_builders_on_primary_language_and_active"
      t.index ["source_dataset"], name: "index_builders_on_source_dataset"
    end

    add_foreign_key "builders", "people"
  end
end
