# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateReleaseEvents < ActiveRecord::Migration[8.1]
  def change
    create_table "release_events" do |t|
      t.string "actor"
      t.string "app"
      t.string "command"
      t.decimal "cost", precision: 10, scale: 4
      t.datetime "created_at", null: false
      t.string "idempotency_key"
      t.text "message"
      t.jsonb "metadata", default: {}, null: false
      t.string "model"
      t.datetime "occurred_at", null: false
      t.string "release_slug", null: false
      t.string "repo"
      t.string "sha"
      t.string "source"
      t.string "status", null: false
      t.string "step", null: false
      t.bigint "tokens_in"
      t.bigint "tokens_out"
      t.datetime "updated_at", null: false
      t.string "url"
      t.index ["release_slug", "idempotency_key"], name: "index_release_events_on_release_slug_and_idempotency_key", unique: true, where: "(idempotency_key IS NOT NULL)"
      t.index ["release_slug", "occurred_at"], name: "index_release_events_on_release_slug_and_occurred_at"
      t.index ["release_slug", "step", "status"], name: "index_release_events_on_release_slug_and_step_and_status"
    end

    add_foreign_key "release_events", "releases", column: "release_slug", primary_key: "slug", on_update: :cascade
  end
end
