# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateTaskGrades < ActiveRecord::Migration[8.1]
  def change
    create_table "task_grades" do |t|
      t.bigint "action_grade_id"
      t.datetime "created_at", null: false
      t.jsonb "facts", default: {}, null: false
      t.datetime "graded_at", null: false
      t.string "grader", default: "xan", null: false
      t.text "learning"
      t.string "note_activity_slug"
      t.string "task_slug", null: false
      t.jsonb "tripped", default: [], null: false
      t.datetime "updated_at", null: false
      t.string "verdict", null: false
      t.index ["task_slug"], name: "index_task_grades_on_task_slug", unique: true
      t.index ["verdict"], name: "index_task_grades_on_verdict"
    end

    add_foreign_key "task_grades", "activities", column: "note_activity_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
    add_foreign_key "task_grades", "tasks", column: "task_slug", primary_key: "slug", on_update: :cascade
  end
end
