# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateGithubWorkflowRuns < ActiveRecord::Migration[8.1]
  def change
    create_table "github_workflow_runs" do |t|
      t.string "conclusion"
      t.datetime "created_at", null: false
      t.string "head_branch"
      t.string "head_sha"
      t.string "html_url"
      t.string "pending_environment"
      t.datetime "pending_since"
      t.string "repo", null: false
      t.integer "run_attempt"
      t.bigint "run_id", null: false
      t.datetime "run_started_at"
      t.string "status", null: false
      t.datetime "updated_at", null: false
      t.string "workflow_name"
      t.index ["head_sha"], name: "index_github_workflow_runs_on_head_sha"
      t.index ["pending_environment"], name: "index_github_workflow_runs_on_pending_environment", where: "(pending_environment IS NOT NULL)"
      t.index ["run_id"], name: "index_github_workflow_runs_on_run_id", unique: true
    end
  end
end
