# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateArtistAliases < ActiveRecord::Migration[8.1]
  def change
    create_table "artist_aliases" do |t|
      t.string "artist_slug", null: false
      t.datetime "created_at", null: false
      t.string "locale", default: "en", null: false
      t.string "name", null: false
      t.datetime "updated_at", null: false
      t.index ["artist_slug", "name", "locale"], name: "index_artist_aliases_on_artist_slug_and_name_and_locale", unique: true
      t.index ["name"], name: "index_artist_aliases_on_name"
    end

    add_foreign_key "artist_aliases", "artists", column: "artist_slug", primary_key: "slug", on_update: :cascade
  end
end
