# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateAppearanceReferencePhotos < ActiveRecord::Migration[8.1]
  def change
    create_table "appearance_reference_photos" do |t|
      t.string "appearance_slug", null: false
      t.boolean "chosen", default: false, null: false
      t.datetime "created_at", null: false
      t.float "face_fill"
      t.float "face_score"
      t.integer "face_subjects"
      t.datetime "found_at"
      t.integer "height"
      t.text "image_url", null: false
      t.string "mime_type"
      t.string "operator_verdict"
      t.datetime "operator_verdict_at"
      t.text "page_url"
      t.integer "position"
      t.text "query"
      t.string "rejection_reason"
      t.string "slug", null: false
      t.string "source", null: false
      t.text "thumb_url"
      t.text "title"
      t.datetime "updated_at", null: false
      t.integer "width"
      t.index ["appearance_slug", "chosen"], name: "index_reference_photos_per_look"
      t.index ["appearance_slug", "image_url"], name: "index_reference_photos_unique_per_look", unique: true
      t.index ["appearance_slug", "operator_verdict"], name: "index_reference_photos_verdict_per_look"
      t.index ["slug"], name: "index_appearance_reference_photos_on_slug", unique: true
    end

    add_foreign_key "appearance_reference_photos", "appearances", column: "appearance_slug", primary_key: "slug", on_update: :cascade
  end
end
