# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateSolidQueueScheduledExecutions < ActiveRecord::Migration[8.1]
  def change
    create_table "solid_queue_scheduled_executions" do |t|
      t.datetime "created_at", null: false
      t.bigint "job_id", null: false
      t.integer "priority", default: 0, null: false
      t.string "queue_name", null: false
      t.datetime "scheduled_at", null: false
      t.index ["job_id"], name: "index_solid_queue_scheduled_executions_on_job_id", unique: true
      t.index ["scheduled_at", "priority", "job_id"], name: "index_solid_queue_dispatch_all"
    end

    add_foreign_key "solid_queue_scheduled_executions", "solid_queue_jobs", column: "job_id", on_delete: :cascade
  end
end
