# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateTrackedGithubBuilders < ActiveRecord::Migration[8.1]
  def change
    create_table "tracked_github_builders" do |t|
      t.boolean "active", default: true, null: false
      t.string "category"
      t.string "cohort", null: false
      t.datetime "created_at", null: false
      t.string "display_name"
      t.string "github_login", null: false
      t.text "notes"
      t.datetime "updated_at", null: false
      t.index ["cohort", "active"], name: "index_tracked_github_builders_on_cohort_and_active"
      t.index ["github_login"], name: "index_tracked_github_builders_on_github_login", unique: true
    end
  end
end
