# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateFacts < ActiveRecord::Migration[8.1]
  def change
    create_table "facts" do |t|
      t.datetime "created_at", null: false
      t.string "key", null: false
      t.datetime "recorded_at", null: false
      t.string "recorded_by_session_slug", null: false
      t.datetime "retired_at"
      t.string "sensitivity", default: "ordinary", null: false
      t.string "slug", null: false
      t.string "source_kind", null: false
      t.string "source_note"
      t.string "source_ref", null: false
      t.string "subject_slug", null: false
      t.string "subject_type", null: false
      t.string "superseded_by_slug"
      t.datetime "updated_at", null: false
      t.text "value"
      t.index ["recorded_by_session_slug"], name: "index_facts_on_recorded_by_session_slug"
      t.index ["slug"], name: "index_facts_on_slug", unique: true
      t.index ["subject_type", "subject_slug", "key"], name: "index_facts_on_subject_type_and_subject_slug_and_key"
      t.index ["superseded_by_slug"], name: "index_facts_on_superseded_by_slug"
    end

    add_foreign_key "facts", "agent_sessions", column: "recorded_by_session_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "facts", "facts", column: "superseded_by_slug", primary_key: "slug", on_update: :cascade
  end
end
