# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateVideoStitches < ActiveRecord::Migration[8.1]
  def change
    create_table "video_stitches" do |t|
      t.string "alt_video_slug", null: false
      t.bigint "byte_size"
      t.datetime "created_at", null: false
      t.integer "duration_ms"
      t.string "failure_reason"
      t.datetime "finished_at"
      t.string "frame_rate"
      t.integer "height"
      t.string "music_video_slug", null: false
      t.integer "number", null: false
      t.string "object_key", null: false
      t.datetime "started_at"
      t.string "state", default: "requested", null: false
      t.jsonb "takes", default: [], null: false
      t.datetime "updated_at", null: false
      t.jsonb "warnings", default: [], null: false
      t.integer "width"
      t.index ["alt_video_slug", "number"], name: "index_video_stitches_on_alt_video_slug_and_number", unique: true
      t.index ["object_key"], name: "index_video_stitches_on_object_key", unique: true
    end

    add_foreign_key "video_stitches", "alt_videos", column: "alt_video_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "video_stitches", "music_videos", column: "music_video_slug", primary_key: "slug", on_update: :cascade
  end
end
