# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateEmailBrandReferences < ActiveRecord::Migration[8.1]
  def change
    create_table "email_brand_references" do |t|
      t.datetime "archived_at"
      t.string "brand_kit", null: false
      t.integer "byte_size", null: false
      t.string "content_type", null: false
      t.datetime "created_at", null: false
      t.integer "height"
      t.text "image_url", null: false
      t.string "label", null: false
      t.text "note"
      t.string "role", null: false
      t.string "slug", null: false
      t.datetime "updated_at", null: false
      t.string "uploaded_by"
      t.integer "width"
      t.index ["brand_kit", "archived_at"], name: "index_email_brand_references_on_brand_kit_and_archived_at"
      t.index ["slug"], name: "index_email_brand_references_on_slug", unique: true
    end
  end
end
