# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateThemeSettings < ActiveRecord::Migration[8.1]
  def change
    create_table "theme_settings" do |t|
      t.string "accent1"
      t.string "accent2"
      t.string "app_name", null: false
      t.datetime "created_at", null: false
      t.string "danger"
      t.string "dark"
      t.string "light"
      t.string "primary"
      t.string "slug"
      t.datetime "updated_at", null: false
      t.string "warning"
      t.index ["app_name"], name: "index_theme_settings_on_app_name", unique: true
    end
  end
end
