# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateApps < ActiveRecord::Migration[8.1]
  def change
    create_table "apps" do |t|
      t.string "color"
      t.datetime "created_at", null: false
      t.text "description"
      t.string "emoji"
      t.string "name", null: false
      t.integer "position", default: 0
      t.string "slug", null: false
      t.string "status", default: "active"
      t.datetime "updated_at", null: false
      t.index ["slug"], name: "index_apps_on_slug", unique: true
    end
  end
end
