# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateGateRuns < ActiveRecord::Migration[8.1]
  def change
    create_table "gate_runs" do |t|
      t.string "actor"
      t.integer "attempt", null: false
      t.datetime "created_at", null: false
      t.datetime "finished_at"
      t.string "key", null: false
      t.jsonb "metadata", default: {}, null: false
      t.jsonb "sops", default: [], null: false
      t.string "source"
      t.datetime "started_at", null: false
      t.string "subject_slug", null: false
      t.string "subject_type", null: false
      t.boolean "success"
      t.datetime "updated_at", null: false
      t.index ["subject_slug", "started_at"], name: "index_gate_runs_on_subject_slug_and_started_at"
      t.index ["subject_type", "subject_slug", "key", "attempt"], name: "index_gate_runs_on_subject_key_attempt", unique: true
      t.index ["subject_type", "subject_slug", "key"], name: "index_gate_runs_one_open_per_gate", unique: true, where: "(finished_at IS NULL)"
    end
  end
end
