# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateSessionMascots < ActiveRecord::Migration[8.1]
  def change
    create_table "session_mascots" do |t|
      t.datetime "created_at", null: false
      t.string "gender"
      t.string "mascot_slug", null: false
      t.string "parent_session_id"
      t.string "session_id", null: false
      t.boolean "shiny", default: false, null: false
      t.datetime "updated_at", null: false
      t.index ["parent_session_id"], name: "index_session_mascots_on_parent_session_id"
      t.index ["session_id"], name: "index_session_mascots_on_session_id", unique: true
    end
  end
end
