# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateCredentialVaults < ActiveRecord::Migration[8.1]
  def change
    create_table "credential_vaults" do |t|
      t.datetime "created_at", null: false
      t.string "entity", null: false
      t.string "icon_scope"
      t.string "lane", null: false
      t.string "name", null: false
      t.text "purpose"
      t.string "slug", null: false
      t.string "status", default: "active", null: false
      t.datetime "updated_at", null: false
      t.string "workspace_domain"
      t.index ["slug"], name: "index_credential_vaults_on_slug", unique: true
      t.index ["workspace_domain"], name: "index_credential_vaults_on_workspace_domain"
    end
  end
end
