# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateAppearances < ActiveRecord::Migration[8.1]
  def change
    create_table "appearances" do |t|
      t.string "base_appearance_slug"
      t.string "character_slug"
      t.string "colorway"
      t.datetime "created_at", null: false
      t.string "descriptor", null: false
      t.text "generation_notes"
      t.string "higgsfield_reference_id"
      t.datetime "higgsfield_reference_minted_at"
      t.string "higgsfield_reference_status"
      t.datetime "higgsfield_reference_synced_at"
      t.boolean "iced", default: false, null: false
      t.integer "jersey_number"
      t.string "music_video_slug"
      t.integer "performer_ordinal"
      t.string "person_slug"
      t.integer "position"
      t.string "reference_url"
      t.datetime "retired_at"
      t.text "sheet_build_error"
      t.datetime "sheet_build_finished_at"
      t.datetime "sheet_build_started_at"
      t.string "sheet_build_state"
      t.string "slug", null: false
      t.string "stage"
      t.string "team_slug"
      t.datetime "updated_at", null: false
      t.index ["base_appearance_slug"], name: "index_appearances_one_live_twin_per_base", unique: true, where: "((base_appearance_slug IS NOT NULL) AND (retired_at IS NULL))"
      t.index ["character_slug", "descriptor"], name: "index_appearances_live_per_character", unique: true, where: "(retired_at IS NULL)"
      t.index ["character_slug"], name: "index_appearances_on_character_slug"
      t.index ["higgsfield_reference_id"], name: "index_appearances_on_higgsfield_reference_id", unique: true, where: "(higgsfield_reference_id IS NOT NULL)"
      t.index ["music_video_slug", "performer_ordinal"], name: "index_appearances_one_live_look_per_performer", unique: true, where: "((music_video_slug IS NOT NULL) AND (retired_at IS NULL))"
      t.index ["person_slug", "descriptor"], name: "index_appearances_live_per_person", unique: true, where: "(retired_at IS NULL)"
      t.index ["slug"], name: "index_appearances_on_slug", unique: true
      t.index ["stage", "position"], name: "index_appearances_board_rank", where: "(retired_at IS NULL)"
      t.check_constraint "num_nonnulls(person_slug, character_slug) = 1", name: "appearances_exactly_one_owner"
    end

    add_foreign_key "appearances", "appearances", column: "base_appearance_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
    add_foreign_key "appearances", "music_videos", column: "music_video_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
    add_foreign_key "appearances", "people", column: "person_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "people", "appearances", column: "default_appearance_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
