# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateAgentActivities < ActiveRecord::Migration[8.1]
  def change
    create_table "agent_activities" do |t|
      t.string "agent"
      t.bigint "cache_creation_tokens"
      t.bigint "cache_read_tokens"
      t.string "category", null: false
      t.datetime "closed_at"
      t.decimal "cost", precision: 10, scale: 4
      t.datetime "created_at", null: false
      t.text "key_method"
      t.string "key_method_lang"
      t.string "mascot"
      t.string "model"
      t.datetime "opened_at", null: false
      t.string "outcome_slug"
      t.bigint "parent_span_id"
      t.string "reason_slug", null: false
      t.integer "seq", default: 0, null: false
      t.string "session_id", null: false
      t.string "stage"
      t.string "supervisor_agent"
      t.string "task_slug"
      t.bigint "tokens_in"
      t.bigint "tokens_out"
      t.string "transcript_path"
      t.string "turn_uuid"
      t.datetime "updated_at", null: false
      t.index ["model", "opened_at"], name: "index_agent_activities_on_model_and_opened_at"
      t.index ["opened_at"], name: "index_agent_activities_on_opened_at"
      t.index ["parent_span_id"], name: "index_agent_activities_on_parent_span_id"
      t.index ["session_id", "closed_at"], name: "index_agent_activities_on_session_id_and_closed_at"
      t.index ["session_id", "seq"], name: "index_agent_activities_on_session_id_and_seq"
      t.index ["session_id", "transcript_path"], name: "index_agent_activities_on_session_and_transcript"
      t.index ["session_id", "turn_uuid"], name: "index_agent_activities_on_session_and_turn", unique: true, where: "(turn_uuid IS NOT NULL)"
      t.index ["task_slug", "seq"], name: "index_agent_activities_on_task_slug_and_seq"
    end

    add_foreign_key "agent_activities", "tasks", column: "task_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
