# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateGithubObservationWindows < ActiveRecord::Migration[8.1]
  def change
    create_table "github_observation_windows" do |t|
      t.datetime "created_at", null: false
      t.datetime "observed_through_at"
      t.datetime "updated_at", null: false
    end
  end
end
