# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
# The view's SQL lives in db/views/release_timeline.sql. A view never dumps to schema.rb.
class CreateReleaseTimelineView < ActiveRecord::Migration[8.1]
  def up
    execute(<<~SQL)
      CREATE VIEW release_timeline AS
      SELECT
        slug, state, created_at, updated_at,
        testing_started_at, tested_at,
        assembling_started_at, assembled_at,
        qa_deploy_started_at, qa_deployed_at,
        confirming_started_at, confirmed_at,
        prod_deploy_started_at, shipped_at,
        abandoned_at, release_notes_sent_at, duration_metrics_cached_at
      FROM releases
    SQL
  end

  def down
    execute("DROP VIEW IF EXISTS release_timeline")
  end
end
