# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateGithubBuilderWeeklyMetrics < ActiveRecord::Migration[8.1]
  def change
    create_table "github_builder_weekly_metrics" do |t|
      t.integer "active_repos_count", default: 0, null: false
      t.decimal "bot_adjusted_builder_multiple", precision: 12, scale: 4
      t.integer "bot_adjusted_commits_count", default: 0, null: false
      t.decimal "builder_multiple", precision: 12, scale: 4
      t.string "cohort", null: false
      t.integer "commits_count", default: 0, null: false
      t.datetime "created_at", null: false
      t.string "github_login", null: false
      t.integer "non_merge_commits_count", default: 0, null: false
      t.decimal "trailing_90d_avg_weekly_commits", precision: 12, scale: 4
      t.datetime "updated_at", null: false
      t.date "week_start_date", null: false
      t.index ["github_login", "week_start_date"], name: "index_builder_weekly_metrics_on_login_week", unique: true
      t.index ["week_start_date", "cohort"], name: "idx_on_week_start_date_cohort_0406de51f1"
    end
  end
end
