# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateEmailEvents < ActiveRecord::Migration[8.1]
  def change
    create_table "email_events" do |t|
      t.bigint "broadcast_delivery_id", null: false
      t.datetime "created_at", null: false
      t.jsonb "data", default: {}, null: false
      t.string "kind", null: false
      t.string "link_key"
      t.boolean "machine", default: false, null: false
      t.datetime "occurred_at", null: false
      t.string "provider_event_id"
      t.string "source", null: false
      t.datetime "updated_at", null: false
      t.index ["broadcast_delivery_id", "kind"], name: "index_email_events_on_broadcast_delivery_id_and_kind"
      t.index ["broadcast_delivery_id"], name: "index_email_events_on_broadcast_delivery_id"
      t.index ["occurred_at"], name: "index_email_events_on_occurred_at"
      t.index ["provider_event_id"], name: "index_email_events_on_provider_event_id", unique: true, where: "(provider_event_id IS NOT NULL)"
    end

    add_foreign_key "email_events", "broadcast_deliveries"
  end
end
