# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateVideoClips < ActiveRecord::Migration[8.1]
  def change
    create_table "video_clips" do |t|
      t.string "cast_shape", null: false
      t.datetime "created_at", null: false
      t.integer "end_ms", null: false
      t.string "kind", default: "candidate", null: false
      t.string "music_video_slug", null: false
      t.string "object_key", null: false
      t.integer "ordinal", null: false
      t.jsonb "performer_ordinals", default: [], null: false
      t.text "prompt", null: false
      t.jsonb "reference_frames", default: [], null: false
      t.string "regenerate_note"
      t.datetime "regenerate_requested_at"
      t.string "seam"
      t.integer "seam_ms"
      t.integer "start_ms", null: false
      t.string "status", default: "proposed", null: false
      t.integer "target_performer"
      t.datetime "updated_at", null: false
      t.index ["music_video_slug", "kind", "ordinal"], name: "index_video_clips_on_music_video_slug_and_kind_and_ordinal", unique: true
    end

    add_foreign_key "video_clips", "music_videos", column: "music_video_slug", primary_key: "slug", on_update: :cascade
  end
end
