# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateTrackedGithubBuilderRepos < ActiveRecord::Migration[8.1]
  def change
    create_table "tracked_github_builder_repos" do |t|
      t.boolean "active", default: true, null: false
      t.datetime "created_at", null: false
      t.string "repo_category"
      t.string "repo_full_name", null: false
      t.bigint "tracked_github_builder_id", null: false
      t.datetime "updated_at", null: false
      t.index ["repo_full_name"], name: "index_tracked_github_builder_repos_on_repo_full_name"
      t.index ["tracked_github_builder_id", "repo_full_name"], name: "index_builder_repos_on_builder_and_repo", unique: true
      t.index ["tracked_github_builder_id"], name: "index_builder_repos_on_builder_id"
    end

    add_foreign_key "tracked_github_builder_repos", "tracked_github_builders"
  end
end
