# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateNews < ActiveRecord::Migration[8.1]
  def change
    create_table "news" do |t|
      t.datetime "archived_at"
      t.string "article_image_url"
      t.string "author"
      t.jsonb "callback_ideas", default: []
      t.datetime "concluded_at"
      t.datetime "created_at", null: false
      t.string "feeling"
      t.string "feeling_emoji"
      t.text "opinion"
      t.integer "position"
      t.string "primary_action"
      t.string "primary_person"
      t.string "primary_person_slug"
      t.string "primary_team"
      t.string "primary_team_slug"
      t.datetime "processed_at"
      t.datetime "published_at"
      t.datetime "refined_at"
      t.datetime "reviewed_at"
      t.string "secondary_person"
      t.string "secondary_person_slug"
      t.string "secondary_team"
      t.string "secondary_team_slug"
      t.string "slug", null: false
      t.string "stage", default: "new", null: false
      t.text "summary"
      t.string "title", null: false
      t.string "title_short"
      t.datetime "updated_at", null: false
      t.string "url"
      t.string "what_happened"
      t.string "x_post_id"
      t.string "x_post_url"
      t.index ["primary_person_slug"], name: "index_news_on_primary_person_slug"
      t.index ["primary_team_slug"], name: "index_news_on_primary_team_slug"
      t.index ["secondary_person_slug"], name: "index_news_on_secondary_person_slug"
      t.index ["secondary_team_slug"], name: "index_news_on_secondary_team_slug"
      t.index ["slug"], name: "index_news_on_slug", unique: true
      t.index ["stage", "position"], name: "index_news_on_stage_and_position"
      t.index ["stage"], name: "index_news_on_stage"
    end

    add_foreign_key "news", "people", column: "primary_person_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
    add_foreign_key "news", "people", column: "secondary_person_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
    add_foreign_key "news", "teams", column: "primary_team_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
    add_foreign_key "news", "teams", column: "secondary_team_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
