# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateDeskRecords < ActiveRecord::Migration[8.1]
  def change
    create_table "desk_records" do |t|
      t.string "actor"
      t.string "ahead"
      t.integer "app_port"
      t.string "app_slug"
      t.string "base_ref"
      t.string "behind"
      t.string "branch"
      t.boolean "cleanup_candidate", default: false, null: false
      t.string "commit_subject"
      t.datetime "created_at", null: false
      t.string "database"
      t.string "desk_slug"
      t.boolean "dirty", default: false, null: false
      t.string "head"
      t.string "health"
      t.string "label"
      t.datetime "last_seen_at"
      t.jsonb "leaked_processes", default: [], null: false
      t.string "local_url"
      t.boolean "merged", default: false, null: false
      t.jsonb "payload", default: {}, null: false
      t.text "rationale"
      t.text "reason"
      t.datetime "recorded_at"
      t.integer "redis_db"
      t.date "resolved_on"
      t.text "safe_delete_condition"
      t.string "safety"
      t.string "source"
      t.string "status", default: "live", null: false
      t.string "task_slug"
      t.string "task_url"
      t.datetime "updated_at", null: false
      t.text "withheld_reason"
      t.string "worktree_path", null: false
      t.index "((payload ->> 'import_key'::text))", name: "index_desk_records_on_import_key", unique: true, where: "((payload ->> 'import_key'::text) IS NOT NULL)"
      t.index ["app_slug"], name: "index_desk_records_on_app_slug"
      t.index ["last_seen_at"], name: "index_desk_records_on_last_seen_at"
      t.index ["resolved_on"], name: "index_desk_records_on_resolved_on"
      t.index ["status"], name: "index_desk_records_on_status"
      t.index ["worktree_path", "resolved_on"], name: "index_desk_records_on_worktree_path_and_resolved_on"
    end

    add_foreign_key "desk_records", "apps", column: "app_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
    add_foreign_key "desk_records", "tasks", column: "task_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
