# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateAltVideoClipVersions < ActiveRecord::Migration[8.1]
  def change
    create_table "alt_video_clip_versions" do |t|
      t.bigint "alt_video_clip_id", null: false
      t.bigint "byte_size", null: false
      t.datetime "created_at", null: false
      t.integer "number", null: false
      t.string "object_key", null: false
      t.string "original_filename"
      t.datetime "primary_since", null: false
      t.datetime "updated_at", null: false
      t.index ["alt_video_clip_id", "number"], name: "index_alt_video_clip_versions_on_alt_video_clip_id_and_number", unique: true
      t.index ["object_key"], name: "index_alt_video_clip_versions_on_object_key", unique: true
    end

    add_foreign_key "alt_video_clip_versions", "alt_video_clips"
  end
end
