# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateArtists < ActiveRecord::Migration[8.1]
  def change
    create_table "artists" do |t|
      t.datetime "created_at", null: false
      t.string "discogs_id"
      t.string "kind", null: false
      t.string "musicbrainz_id"
      t.string "name", null: false
      t.string "person_slug"
      t.string "slug", null: false
      t.string "sort_name", null: false
      t.string "spotify_id"
      t.datetime "updated_at", null: false
      t.string "wikidata_id"
      t.index ["musicbrainz_id"], name: "index_artists_on_musicbrainz_id"
      t.index ["name"], name: "index_artists_on_name"
      t.index ["person_slug"], name: "index_artists_on_person_slug"
      t.index ["slug"], name: "index_artists_on_slug", unique: true
      t.index ["spotify_id"], name: "index_artists_on_spotify_id"
      t.index ["wikidata_id"], name: "index_artists_on_wikidata_id", unique: true
    end

    add_foreign_key "artists", "people", column: "person_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
