# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateAgentSessions < ActiveRecord::Migration[8.1]
  def change
    create_table "agent_sessions" do |t|
      t.datetime "created_at", null: false
      t.datetime "expires_at", null: false
      t.string "harness_session_id"
      t.datetime "issued_at", null: false
      t.string "issued_by", null: false
      t.datetime "revoked_at"
      t.string "revoked_by"
      t.string "slug", null: false
      t.string "soul", null: false
      t.string "task_slug"
      t.string "tier", null: false
      t.datetime "updated_at", null: false
      t.index ["slug"], name: "index_agent_sessions_on_slug", unique: true
      t.index ["soul", "tier"], name: "index_agent_sessions_on_soul_and_tier"
      t.index ["task_slug", "revoked_at"], name: "index_agent_sessions_on_task_slug_and_revoked_at"
    end

    add_foreign_key "agent_sessions", "tasks", column: "task_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
