# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateReviewPendingActions < ActiveRecord::Migration[8.1]
  def change
    create_table "review_pending_actions" do |t|
      t.string "action", default: "merge_to_accepted", null: false
      t.integer "attempts", default: 0, null: false
      t.string "authorized_by"
      t.string "base_branch", default: "accepted", null: false
      t.datetime "created_at", null: false
      t.datetime "executed_at"
      t.datetime "expires_at", null: false
      t.string "head_sha", null: false
      t.datetime "last_attempted_at"
      t.string "merge_method", default: "merge", null: false
      t.string "merge_sha"
      t.jsonb "metadata", default: {}, null: false
      t.text "outcome_reason"
      t.integer "pr_number", null: false
      t.string "pr_url"
      t.string "repo", null: false
      t.string "state", default: "pending", null: false
      t.string "task_slug", null: false
      t.datetime "updated_at", null: false
      t.string "verdict", null: false
      t.bigint "verdict_activity_id"
      t.datetime "verdict_recorded_at"
      t.index ["repo", "head_sha"], name: "index_review_pending_actions_on_repo_and_head_sha"
      t.index ["state", "expires_at"], name: "index_review_pending_actions_on_state_and_expires_at"
      t.index ["task_slug"], name: "index_review_pending_actions_on_live_task_slug", unique: true, where: "((state)::text = 'pending'::text)"
      t.index ["task_slug"], name: "index_review_pending_actions_on_task_slug"
    end

    add_foreign_key "review_pending_actions", "tasks", column: "task_slug", primary_key: "slug", on_update: :cascade, on_delete: :cascade
  end
end
