# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateGithubCommitObservations < ActiveRecord::Migration[8.1]
  def change
    create_table "github_commit_observations" do |t|
      t.string "author_login"
      t.datetime "authored_at"
      t.datetime "committed_at"
      t.string "committer_login"
      t.datetime "created_at", null: false
      t.string "github_login", null: false
      t.string "html_url"
      t.boolean "is_bot", default: false, null: false
      t.boolean "is_merge", default: false, null: false
      t.text "message"
      t.jsonb "raw_payload", default: {}, null: false
      t.string "repo_full_name", null: false
      t.string "sha", null: false
      t.string "source_strategy", null: false
      t.datetime "updated_at", null: false
      t.index ["github_login", "authored_at"], name: "idx_on_github_login_authored_at_00ca1cd94c"
      t.index ["github_login", "committed_at"], name: "idx_on_github_login_committed_at_810ec88674"
      t.index ["repo_full_name", "sha", "github_login"], name: "index_commit_observations_on_repo_sha_login", unique: true
      t.index ["source_strategy"], name: "index_github_commit_observations_on_source_strategy"
    end
  end
end
