# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateAltVideos < ActiveRecord::Migration[8.1]
  def change
    create_table "alt_videos" do |t|
      t.datetime "created_at", null: false
      t.string "music_video_slug", null: false
      t.integer "number", null: false
      t.string "slug", null: false
      t.jsonb "swaps", default: [], null: false
      t.datetime "updated_at", null: false
      t.index ["music_video_slug", "number"], name: "index_alt_videos_on_music_video_slug_and_number", unique: true
      t.index ["slug"], name: "index_alt_videos_on_slug", unique: true
    end

    add_foreign_key "alt_videos", "music_videos", column: "music_video_slug", primary_key: "slug", on_update: :cascade
  end
end
