# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateUsages < ActiveRecord::Migration[8.1]
  def change
    create_table "usages" do |t|
      t.string "agent_slug"
      t.integer "api_calls", default: 0
      t.decimal "cost", precision: 10, scale: 4, default: "0.0"
      t.datetime "created_at", null: false
      t.jsonb "metadata", default: {}
      t.string "model"
      t.date "period_date", null: false
      t.string "period_type", null: false
      t.string "slug"
      t.integer "tasks_completed", default: 0
      t.integer "tasks_failed", default: 0
      t.bigint "tokens_in", default: 0
      t.bigint "tokens_out", default: 0
      t.datetime "updated_at", null: false
      t.index ["agent_slug", "period_date", "period_type", "model"], name: "idx_usages_unique", unique: true
      t.index ["agent_slug"], name: "index_usages_on_agent_slug"
      t.index ["slug"], name: "index_usages_on_slug", unique: true
    end

    add_foreign_key "usages", "agents", column: "agent_slug", primary_key: "slug", on_update: :cascade
  end
end
