# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
# The view's SQL lives in db/views/task_timeline.sql. A view never dumps to schema.rb.
class CreateTaskTimelineView < ActiveRecord::Migration[8.1]
  def up
    execute(<<~SQL)
      CREATE VIEW task_timeline AS
      SELECT
        slug, title, stage, blocked_at, blocked_from, blocked_by, block_kind,
        created_at, updated_at,
        queued_at, sizes_revealed_at, started_at,
        g1_testing_started_at, g1_testing_finished_at, g1_failed_at,
        submitted_at, reviewed_at, assembled_at, completed_at, archived_at,
        gates_cached_at, testing_phases_cached_at
      FROM tasks
    SQL
  end

  def down
    execute("DROP VIEW IF EXISTS task_timeline")
  end
end
