# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateGithubBuilderCommitRangeCaches < ActiveRecord::Migration[8.1]
  def change
    create_table "github_builder_commit_range_caches" do |t|
      t.integer "active_repos_count", default: 0, null: false
      t.decimal "bot_adjusted_builder_multiple", precision: 12, scale: 4
      t.integer "bot_adjusted_commits_count", default: 0, null: false
      t.decimal "builder_multiple", precision: 12, scale: 4
      t.string "cache_run_key", default: "legacy", null: false
      t.datetime "cached_at", null: false
      t.string "cohort", null: false
      t.jsonb "commit_shas", default: [], null: false
      t.integer "commits_count", default: 0, null: false
      t.datetime "created_at", null: false
      t.bigint "github_commit_range_id", null: false
      t.string "github_login", null: false
      t.integer "non_merge_commits_count", default: 0, null: false
      t.bigint "tracked_github_builder_id", null: false
      t.decimal "trailing_90d_avg_weekly_commits", precision: 12, scale: 4
      t.datetime "updated_at", null: false
      t.index ["cache_run_key", "tracked_github_builder_id", "github_commit_range_id"], name: "idx_builder_range_caches_on_run_key_builder_range"
      t.index ["cache_run_key"], name: "idx_builder_range_caches_on_cache_run_key"
      t.index ["github_commit_range_id", "cohort"], name: "idx_builder_range_caches_on_range_cohort"
      t.index ["github_commit_range_id"], name: "index_builder_range_caches_on_range_id"
      t.index ["github_login", "github_commit_range_id"], name: "idx_builder_range_caches_on_login_range"
      t.index ["tracked_github_builder_id", "github_commit_range_id"], name: "idx_builder_range_caches_on_builder_range", unique: true
      t.index ["tracked_github_builder_id"], name: "index_builder_range_caches_on_builder_id"
    end

    add_foreign_key "github_builder_commit_range_caches", "github_commit_ranges"
    add_foreign_key "github_builder_commit_range_caches", "tracked_github_builders"
  end
end
