# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateStudioEmailDeliveries < ActiveRecord::Migration[8.1]
  def change
    create_table "studio_email_deliveries" do |t|
      t.string "action", null: false
      t.jsonb "args", default: [], null: false
      t.datetime "created_at", null: false
      t.string "email_key", null: false
      t.text "error"
      t.jsonb "kwargs", default: {}, null: false
      t.string "mailer", null: false
      t.boolean "sent", default: false, null: false
      t.datetime "sent_at"
      t.string "to"
      t.datetime "updated_at", null: false
      t.bigint "user_id"
      t.index ["created_at"], name: "index_studio_email_deliveries_on_created_at"
      t.index ["email_key"], name: "index_studio_email_deliveries_on_email_key"
      t.index ["sent"], name: "index_studio_email_deliveries_on_sent"
      t.index ["user_id"], name: "index_studio_email_deliveries_on_user_id"
    end

    add_foreign_key "studio_email_deliveries", "users"
  end
end
