# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateCharacters < ActiveRecord::Migration[8.1]
  def change
    create_table "characters" do |t|
      t.string "avatar_url"
      t.text "bio"
      t.string "brand"
      t.datetime "created_at", null: false
      t.string "default_appearance_slug"
      t.string "kind", null: false
      t.string "name", null: false
      t.text "personality"
      t.datetime "retired_at"
      t.string "slug", null: false
      t.datetime "updated_at", null: false
      t.text "voice_notes"
      t.index ["brand"], name: "index_characters_on_brand"
      t.index ["slug"], name: "index_characters_on_slug", unique: true
      t.check_constraint "kind::text = ANY (ARRAY['mascot'::character varying::text, 'puppet'::character varying::text])", name: "characters_kind_known"
    end

    add_foreign_key "appearances", "characters", column: "character_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "characters", "appearances", column: "default_appearance_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
