# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateStudioEnumerals < ActiveRecord::Migration[8.1]
  def change
    create_table "studio_enumerals" do |t|
      t.string "category", null: false
      t.string "color"
      t.datetime "created_at", null: false
      t.string "key", null: false
      t.string "label"
      t.jsonb "metadata", default: {}, null: false
      t.integer "position", default: 0, null: false
      t.integer "rank"
      t.datetime "updated_at", null: false
      t.index ["category", "key"], name: "index_studio_enumerals_on_category_and_key", unique: true
      t.index ["category", "position"], name: "index_studio_enumerals_on_category_and_position"
      t.index ["category", "rank"], name: "index_studio_enumerals_on_category_and_rank"
    end
  end
end
