# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateSolidQueuePauses < ActiveRecord::Migration[8.1]
  def change
    create_table "solid_queue_pauses" do |t|
      t.datetime "created_at", null: false
      t.string "queue_name", null: false
      t.index ["queue_name"], name: "index_solid_queue_pauses_on_queue_name", unique: true
    end
  end
end
