# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateStudioLinks < ActiveRecord::Migration[8.1]
  def change
    create_table "studio_links" do |t|
      t.datetime "consumed_at"
      t.datetime "created_at", null: false
      t.datetime "expires_at"
      t.string "kind", null: false
      t.bigint "linkable_id"
      t.string "linkable_type"
      t.jsonb "metadata", default: {}, null: false
      t.string "token", null: false
      t.datetime "updated_at", null: false
      t.index ["kind"], name: "index_studio_links_on_kind"
      t.index ["linkable_type", "linkable_id", "kind"], name: "idx_studio_links_owner_kind"
      t.index ["token"], name: "index_studio_links_on_token", unique: true
    end
  end
end
