# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateActivities < ActiveRecord::Migration[8.1]
  def change
    create_table "activities" do |t|
      t.string "activity_type"
      t.string "agent_slug"
      t.datetime "created_at", null: false
      t.text "description"
      t.jsonb "metadata", default: {}
      t.string "slug"
      t.string "task_slug"
      t.datetime "updated_at", null: false
      t.index ["activity_type", "created_at"], name: "index_activities_on_activity_type_and_created_at"
      t.index ["activity_type"], name: "index_activities_on_activity_type"
      t.index ["agent_slug"], name: "index_activities_on_agent_slug"
      t.index ["slug"], name: "index_activities_on_slug", unique: true
      t.index ["task_slug"], name: "index_activities_on_task_slug"
    end

    add_foreign_key "activities", "agents", column: "agent_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "activities", "tasks", column: "task_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
