# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateSolidQueueRecurringTasks < ActiveRecord::Migration[8.1]
  def change
    create_table "solid_queue_recurring_tasks" do |t|
      t.text "arguments"
      t.string "class_name"
      t.string "command", limit: 2048
      t.datetime "created_at", null: false
      t.text "description"
      t.string "key", null: false
      t.integer "priority", default: 0
      t.string "queue_name"
      t.string "schedule", null: false
      t.boolean "static", default: true, null: false
      t.datetime "updated_at", null: false
      t.index ["key"], name: "index_solid_queue_recurring_tasks_on_key", unique: true
      t.index ["static"], name: "index_solid_queue_recurring_tasks_on_static"
    end
  end
end
