# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateAthleteGrades < ActiveRecord::Migration[8.1]
  def change
    create_table "athlete_grades" do |t|
      t.string "athlete_slug", null: false
      t.float "coverage_grade_pff"
      t.datetime "created_at", null: false
      t.float "defense_grade_pff"
      t.float "fg_grade_pff"
      t.integer "games_played"
      t.jsonb "grade_ranges"
      t.float "kickoff_grade_pff"
      t.float "offense_grade_pff"
      t.float "overall_grade_pff"
      t.float "pass_block_grade_pff"
      t.float "pass_grade_pff"
      t.float "pass_route_grade_pff"
      t.float "pass_rush_grade_pff"
      t.integer "position_pass_grade"
      t.integer "position_pass_rank"
      t.integer "position_run_grade"
      t.integer "position_run_rank"
      t.float "punting_grade_pff"
      t.float "return_grade_pff"
      t.float "run_block_grade_pff"
      t.float "run_grade_pff"
      t.float "rush_defense_grade_pff"
      t.string "season_slug", null: false
      t.string "slug", null: false
      t.integer "snaps"
      t.datetime "updated_at", null: false
      t.index ["athlete_slug", "season_slug"], name: "index_athlete_grades_on_athlete_slug_and_season_slug", unique: true
      t.index ["athlete_slug"], name: "index_athlete_grades_on_athlete_slug"
      t.index ["position_pass_rank"], name: "index_athlete_grades_on_position_pass_rank"
      t.index ["position_run_rank"], name: "index_athlete_grades_on_position_run_rank"
      t.index ["season_slug"], name: "index_athlete_grades_on_season_slug"
      t.index ["slug"], name: "index_athlete_grades_on_slug", unique: true
    end

    add_foreign_key "athlete_grades", "athletes", column: "athlete_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "athlete_grades", "seasons", column: "season_slug", primary_key: "slug", on_update: :cascade
  end
end
