# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateEmailImageBriefs < ActiveRecord::Migration[8.1]
  def change
    create_table "email_image_briefs" do |t|
      t.string "alt_text"
      t.string "app", null: false
      t.string "approved_artifact_slug"
      t.string "brand_kit", null: false
      t.text "build_error"
      t.datetime "build_finished_at"
      t.datetime "build_started_at"
      t.string "build_state"
      t.datetime "created_at", null: false
      t.string "created_by"
      t.string "email_key", null: false
      t.datetime "exported_at"
      t.string "exported_to"
      t.string "generator_key"
      t.string "headline", null: false
      t.string "image_format", default: "jpg", null: false
      t.integer "max_rounds", default: 4, null: false
      t.string "preset", default: "header_2x1", null: false
      t.text "prompt_notes"
      t.integer "rounds_used", default: 0, null: false
      t.string "slug", null: false
      t.string "subtext"
      t.string "text_mode", default: "baked", null: false
      t.datetime "updated_at", null: false
      t.string "variant", default: "default", null: false
      t.index ["app", "email_key", "variant"], name: "index_email_image_briefs_on_app_and_email_key_and_variant", unique: true
      t.index ["slug"], name: "index_email_image_briefs_on_slug", unique: true
    end

    add_foreign_key "artifacts", "email_image_briefs", column: "brief_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
    add_foreign_key "email_image_briefs", "artifacts", column: "approved_artifact_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
