# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateCiCheckJobs < ActiveRecord::Migration[8.1]
  def change
    create_table "ci_check_jobs" do |t|
      t.datetime "completed_at"
      t.string "conclusion"
      t.datetime "created_at", null: false
      t.string "head_branch"
      t.string "head_sha", null: false
      t.bigint "job_id", null: false
      t.string "name"
      t.string "repo", null: false
      t.bigint "run_id"
      t.datetime "started_at"
      t.string "status", null: false
      t.datetime "updated_at", null: false
      t.string "workflow_name"
      t.index ["job_id"], name: "index_ci_check_jobs_on_job_id", unique: true
      t.index ["repo", "head_sha"], name: "index_ci_check_jobs_on_repo_and_head_sha"
    end
  end
end
