# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateArtistMemberships < ActiveRecord::Migration[8.1]
  def change
    create_table "artist_memberships" do |t|
      t.datetime "created_at", null: false
      t.integer "end_year"
      t.string "group_artist_slug", null: false
      t.string "member_artist_slug", null: false
      t.integer "start_year"
      t.datetime "updated_at", null: false
      t.index "member_artist_slug, group_artist_slug, COALESCE(start_year, 0)", name: "index_artist_memberships_on_stint", unique: true
      t.index ["group_artist_slug"], name: "index_artist_memberships_on_group_artist_slug"
    end

    add_foreign_key "artist_memberships", "artists", column: "group_artist_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "artist_memberships", "artists", column: "member_artist_slug", primary_key: "slug", on_update: :cascade
  end
end
