# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateMusicVideoArtists < ActiveRecord::Migration[8.1]
  def change
    create_table "music_video_artists" do |t|
      t.string "artist_slug", null: false
      t.datetime "created_at", null: false
      t.string "music_video_slug", null: false
      t.integer "position", default: 1, null: false
      t.string "role", null: false
      t.datetime "updated_at", null: false
      t.index ["artist_slug"], name: "index_music_video_artists_on_artist_slug"
      t.index ["music_video_slug", "artist_slug"], name: "index_music_video_artists_on_music_video_slug_and_artist_slug", unique: true
    end

    add_foreign_key "music_video_artists", "artists", column: "artist_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "music_video_artists", "music_videos", column: "music_video_slug", primary_key: "slug", on_update: :cascade
  end
end
