# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateTeamRankings < ActiveRecord::Migration[8.1]
  def change
    create_table "team_rankings" do |t|
      t.datetime "created_at", null: false
      t.integer "rank", null: false
      t.string "rank_type", null: false
      t.decimal "score", precision: 10, scale: 2
      t.string "season_slug", null: false
      t.string "slug", null: false
      t.string "team_slug", null: false
      t.datetime "updated_at", null: false
      t.integer "week"
      t.index ["season_slug"], name: "index_team_rankings_on_season_slug"
      t.index ["slug"], name: "index_team_rankings_on_slug", unique: true
      t.index ["team_slug", "rank_type", "season_slug", "week"], name: "idx_team_rankings_unique_with_week", unique: true, where: "(week IS NOT NULL)"
      t.index ["team_slug", "rank_type", "season_slug"], name: "idx_team_rankings_unique_preseason", unique: true, where: "(week IS NULL)"
      t.index ["team_slug"], name: "index_team_rankings_on_team_slug"
    end

    add_foreign_key "team_rankings", "seasons", column: "season_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "team_rankings", "teams", column: "team_slug", primary_key: "slug", on_update: :cascade
  end
end
