# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateAthletes < ActiveRecord::Migration[8.1]
  def change
    create_table "athletes" do |t|
      t.string "build"
      t.datetime "created_at", null: false
      t.integer "draft_pick"
      t.integer "draft_round"
      t.integer "draft_year"
      t.string "espn_headshot_url"
      t.string "espn_id"
      t.string "gsis_id"
      t.string "hair_description"
      t.integer "height_inches"
      t.integer "jersey_number"
      t.string "nflverse_id"
      t.string "otc_id"
      t.string "person_slug", null: false
      t.integer "pff_id"
      t.string "pfr_id"
      t.string "position"
      t.string "skin_tone"
      t.string "sleeper_id"
      t.string "slug", null: false
      t.string "sport", null: false
      t.string "team_slug"
      t.datetime "updated_at", null: false
      t.integer "weight_lbs"
      t.index ["espn_id"], name: "index_athletes_on_espn_id"
      t.index ["gsis_id"], name: "index_athletes_on_gsis_id", unique: true
      t.index ["nflverse_id"], name: "index_athletes_on_nflverse_id", unique: true
      t.index ["otc_id"], name: "index_athletes_on_otc_id", unique: true
      t.index ["person_slug"], name: "index_athletes_on_person_slug", unique: true
      t.index ["pff_id"], name: "index_athletes_on_pff_id", unique: true
      t.index ["pfr_id"], name: "index_athletes_on_pfr_id", unique: true
      t.index ["position"], name: "index_athletes_on_position"
      t.index ["sleeper_id"], name: "index_athletes_on_sleeper_id", unique: true
      t.index ["slug"], name: "index_athletes_on_slug", unique: true
      t.index ["sport"], name: "index_athletes_on_sport"
      t.index ["team_slug"], name: "index_athletes_on_team_slug"
      t.index ["updated_at"], name: "index_athletes_on_updated_at"
    end

    add_foreign_key "athletes", "people", column: "person_slug", primary_key: "slug", on_update: :cascade
  end
end
