# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateArtifactSubjects < ActiveRecord::Migration[8.1]
  def change
    create_table "artifact_subjects" do |t|
      t.string "appearance_slug"
      t.string "artifact_slug", null: false
      t.string "character_slug"
      t.datetime "created_at", null: false
      t.integer "ordinal", default: 1, null: false
      t.string "person_slug"
      t.string "role"
      t.datetime "updated_at", null: false
      t.index ["appearance_slug"], name: "index_artifact_subjects_on_appearance_slug"
      t.index ["artifact_slug", "character_slug"], name: "index_artifact_subjects_on_artifact_and_character", unique: true, where: "(character_slug IS NOT NULL)"
      t.index ["artifact_slug", "person_slug"], name: "index_artifact_subjects_on_artifact_slug_and_person_slug", unique: true
      t.index ["character_slug"], name: "index_artifact_subjects_on_character_slug"
      t.index ["person_slug"], name: "index_artifact_subjects_on_person_slug"
      t.check_constraint "num_nonnulls(person_slug, character_slug) = 1", name: "artifact_subjects_exactly_one_owner"
    end

    add_foreign_key "artifact_subjects", "appearances", column: "appearance_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
    add_foreign_key "artifact_subjects", "artifacts", column: "artifact_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "artifact_subjects", "characters", column: "character_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "artifact_subjects", "people", column: "person_slug", primary_key: "slug", on_update: :cascade
  end
end
