# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateContacts < ActiveRecord::Migration[8.1]
  def change
    create_table "contacts" do |t|
      t.datetime "created_at", null: false
      t.string "email", null: false
      t.string "first_name"
      t.string "last_name"
      t.string "source"
      t.boolean "subscribed", default: true, null: false
      t.string "tags", default: [], null: false, array: true
      t.jsonb "traits", default: {}, null: false
      t.string "unsubscribe_reason"
      t.string "unsubscribe_token", null: false
      t.datetime "unsubscribed_at"
      t.datetime "updated_at", null: false
      t.string "verification_status"
      t.string "verification_sub_status"
      t.datetime "verified_at"
      t.index "lower((email)::text)", name: "index_contacts_on_lower_email", unique: true
      t.index ["tags"], name: "index_contacts_on_tags", using: :gin
      t.index ["unsubscribe_token"], name: "index_contacts_on_unsubscribe_token", unique: true
      t.index ["verification_status"], name: "index_contacts_on_verification_status"
    end
  end
end
