# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateReleaseConductorClaims < ActiveRecord::Migration[8.1]
  def change
    create_table "release_conductor_claims" do |t|
      t.datetime "acquired_at"
      t.datetime "claim_expires_at"
      t.string "claim_nonce"
      t.string "claimed_session"
      t.datetime "created_at", null: false
      t.string "holder_label"
      t.string "release_slug", null: false
      t.string "role", null: false
      t.datetime "updated_at", null: false
      t.index ["release_slug", "role"], name: "index_release_conductor_claims_on_release_slug_and_role", unique: true
    end
  end
end
