# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateStackClients < ActiveRecord::Migration[8.1]
  def change
    create_table "stack_clients" do |t|
      t.datetime "created_at", null: false
      t.string "domain"
      t.jsonb "extra_software", default: [], null: false
      t.integer "google_users"
      t.jsonb "hosting", default: {}, null: false
      t.string "name", null: false
      t.text "notes"
      t.integer "position", default: 0, null: false
      t.string "resend_mode"
      t.string "slug", null: false
      t.string "tier", null: false
      t.datetime "updated_at", null: false
      t.index ["domain"], name: "index_stack_clients_on_domain"
      t.index ["slug"], name: "index_stack_clients_on_slug", unique: true
    end
  end
end
