# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateDeskCaptureItems < ActiveRecord::Migration[8.1]
  def change
    create_table "desk_capture_items" do |t|
      t.jsonb "attachments", default: [], null: false
      t.text "body_text"
      t.datetime "created_at", null: false
      t.string "entity_hint"
      t.text "filed_note"
      t.string "from_addr"
      t.bigint "history_id"
      t.string "message_id"
      t.datetime "received_at"
      t.string "s3_key", null: false
      t.string "source", default: "resend", null: false
      t.string "status", default: "received", null: false
      t.string "subject"
      t.datetime "updated_at", null: false
      t.index ["s3_key"], name: "index_desk_capture_items_on_s3_key", unique: true
      t.index ["source", "history_id"], name: "index_desk_capture_items_on_source_and_history_id"
      t.index ["status", "received_at"], name: "index_desk_capture_items_on_status_and_received_at"
    end
  end
end
