# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateStagedEmails < ActiveRecord::Migration[8.1]
  def change
    create_table "staged_emails" do |t|
      t.datetime "approved_at"
      t.bigint "broadcast_delivery_id"
      t.bigint "broadcast_id", null: false
      t.datetime "cancelled_at"
      t.bigint "contact_id", null: false
      t.datetime "created_at", null: false
      t.string "delivery_token"
      t.string "email"
      t.jsonb "merge_fields", default: {}, null: false
      t.datetime "queued_at"
      t.text "rendered_html"
      t.string "rendered_subject"
      t.text "rendered_text"
      t.datetime "scheduled_for"
      t.datetime "sent_at"
      t.string "skip_reason"
      t.datetime "staged_at"
      t.string "status", default: "staged", null: false
      t.datetime "updated_at", null: false
      t.index ["broadcast_delivery_id"], name: "index_staged_emails_on_broadcast_delivery_id"
      t.index ["broadcast_id", "contact_id"], name: "index_staged_emails_on_broadcast_id_and_contact_id", unique: true
      t.index ["broadcast_id", "status"], name: "index_staged_emails_on_broadcast_id_and_status"
      t.index ["broadcast_id"], name: "index_staged_emails_on_broadcast_id"
      t.index ["contact_id"], name: "index_staged_emails_on_contact_id"
      t.index ["delivery_token"], name: "index_staged_emails_on_delivery_token", unique: true, where: "(delivery_token IS NOT NULL)"
    end

    add_foreign_key "staged_emails", "broadcast_deliveries", on_delete: :nullify
    add_foreign_key "staged_emails", "broadcasts"
    add_foreign_key "staged_emails", "contacts"
  end
end
