# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateTaskReviewClaims < ActiveRecord::Migration[8.1]
  def change
    create_table "task_review_claims" do |t|
      t.datetime "acquired_at"
      t.datetime "claim_expires_at"
      t.string "claim_nonce"
      t.string "claimed_session"
      t.datetime "created_at", null: false
      t.string "holder_agent"
      t.string "holder_label"
      t.string "task_slug", null: false
      t.datetime "updated_at", null: false
      t.index ["task_slug"], name: "index_task_review_claims_on_task_slug", unique: true
    end

    add_foreign_key "task_review_claims", "tasks", column: "task_slug", primary_key: "slug", on_update: :cascade
  end
end
