# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateWorkspaceAccounts < ActiveRecord::Migration[8.1]
  def change
    create_table "workspace_accounts" do |t|
      t.datetime "created_at", null: false
      t.datetime "delegation_verified_at"
      t.string "domain", null: false
      t.string "entity"
      t.string "last_check_error"
      t.string "name"
      t.text "notes"
      t.jsonb "scopes", default: [], null: false
      t.string "status", default: "pending", null: false
      t.string "subject", null: false
      t.datetime "updated_at", null: false
      t.index ["domain"], name: "index_workspace_accounts_on_domain", unique: true
      t.index ["subject"], name: "index_workspace_accounts_on_subject", unique: true
    end
  end
end
