# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateArenas < ActiveRecord::Migration[8.1]
  def change
    create_table "arenas" do |t|
      t.string "address"
      t.string "city"
      t.string "country"
      t.datetime "created_at", null: false
      t.string "location"
      t.string "name", null: false
      t.string "slug", null: false
      t.string "state"
      t.string "timezone"
      t.datetime "updated_at", null: false
      t.index ["slug"], name: "index_arenas_on_slug", unique: true
    end
  end
end
