# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateBroadcastDeliveries < ActiveRecord::Migration[8.1]
  def change
    create_table "broadcast_deliveries" do |t|
      t.string "bounce_kind"
      t.datetime "bounced_at"
      t.bigint "broadcast_id", null: false
      t.integer "click_count", default: 0, null: false
      t.datetime "clicked_at"
      t.datetime "complained_at"
      t.bigint "contact_id", null: false
      t.datetime "created_at", null: false
      t.datetime "delivered_at"
      t.datetime "human_clicked_at"
      t.datetime "human_opened_at"
      t.integer "open_count", default: 0, null: false
      t.datetime "opened_at"
      t.string "provider_message_id"
      t.datetime "sent_at"
      t.string "token", null: false
      t.datetime "unsubscribed_at"
      t.datetime "updated_at", null: false
      t.index ["broadcast_id", "contact_id"], name: "index_broadcast_deliveries_on_broadcast_id_and_contact_id", unique: true
      t.index ["broadcast_id"], name: "index_broadcast_deliveries_on_broadcast_id"
      t.index ["contact_id"], name: "index_broadcast_deliveries_on_contact_id"
      t.index ["provider_message_id"], name: "index_broadcast_deliveries_on_provider_message_id", unique: true, where: "(provider_message_id IS NOT NULL)"
      t.index ["token"], name: "index_broadcast_deliveries_on_token", unique: true
    end

    add_foreign_key "broadcast_deliveries", "broadcasts"
    add_foreign_key "broadcast_deliveries", "contacts"
  end
end
