# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreatePokemons < ActiveRecord::Migration[8.1]
  def change
    create_table "pokemons" do |t|
      t.integer "attack"
      t.string "avatar_fallback_url"
      t.string "avatar_url"
      t.jsonb "baby", default: [], null: false
      t.string "base"
      t.datetime "created_at", null: false
      t.integer "defense"
      t.integer "dex", null: false
      t.jsonb "evolution", default: [], null: false
      t.jsonb "evolution_genders", default: {}, null: false
      t.string "female_sprite_url"
      t.jsonb "gender_forms", default: {}, null: false
      t.integer "gender_rate"
      t.integer "generation", default: 1, null: false
      t.boolean "has_gender_differences", default: false, null: false
      t.integer "hp"
      t.string "name", null: false
      t.string "primary_type"
      t.string "shiny_avatar_fallback_url"
      t.string "shiny_avatar_url"
      t.string "shiny_female_sprite_url"
      t.string "shiny_sprite_url"
      t.string "slug", null: false
      t.integer "special_attack"
      t.integer "special_defense"
      t.integer "speed"
      t.string "sprite_url"
      t.string "types", default: [], null: false, array: true
      t.datetime "updated_at", null: false
      t.index ["dex"], name: "index_pokemons_on_dex"
      t.index ["slug"], name: "index_pokemons_on_slug", unique: true
    end
  end
end
