# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateSolidQueueFailedExecutions < ActiveRecord::Migration[8.1]
  def change
    create_table "solid_queue_failed_executions" do |t|
      t.datetime "created_at", null: false
      t.text "error"
      t.bigint "job_id", null: false
      t.index ["job_id"], name: "index_solid_queue_failed_executions_on_job_id", unique: true
    end

    add_foreign_key "solid_queue_failed_executions", "solid_queue_jobs", column: "job_id", on_delete: :cascade
  end
end
