# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateAgentLoginRequests < ActiveRecord::Migration[8.1]
  def change
    create_table "agent_login_requests" do |t|
      t.string "agent_session_slug"
      t.integer "code_attempts", default: 0, null: false
      t.string "collect_digest", null: false
      t.datetime "collected_at"
      t.datetime "created_at", null: false
      t.datetime "decided_at"
      t.string "decided_by"
      t.string "harness_session_id", null: false
      t.string "phrase_digest", null: false
      t.string "refusal_reason"
      t.datetime "requested_at", null: false
      t.string "slug", null: false
      t.string "soul", null: false
      t.string "status", default: "pending", null: false
      t.datetime "updated_at", null: false
      t.index ["agent_session_slug"], name: "index_agent_login_requests_on_agent_session_slug"
      t.index ["slug"], name: "index_agent_login_requests_on_slug", unique: true
      t.index ["status", "requested_at"], name: "index_agent_login_requests_on_status_and_requested_at"
    end

    add_foreign_key "agent_login_requests", "agent_sessions", column: "agent_session_slug", primary_key: "slug", on_update: :cascade
  end
end
