# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateWorkspaceMailboxes < ActiveRecord::Migration[8.1]
  def change
    create_table "workspace_mailboxes" do |t|
      t.string "address", null: false
      t.datetime "created_at", null: false
      t.string "last_check_error"
      t.text "notes"
      t.text "signature"
      t.string "status", default: "pending", null: false
      t.datetime "updated_at", null: false
      t.datetime "verified_at"
      t.bigint "workspace_account_id", null: false
      t.index ["address"], name: "index_workspace_mailboxes_on_address", unique: true
      t.index ["workspace_account_id"], name: "index_workspace_mailboxes_on_workspace_account_id"
    end

    add_foreign_key "workspace_mailboxes", "workspace_accounts"
  end
end
