# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateGithubBuilderIndexWeeks < ActiveRecord::Migration[8.1]
  def change
    create_table "github_builder_index_weeks" do |t|
      t.integer "ai_builder_count", default: 0, null: false
      t.decimal "ai_builder_multiple", precision: 12, scale: 4
      t.integer "control_builder_count", default: 0, null: false
      t.decimal "control_builder_multiple", precision: 12, scale: 4
      t.datetime "created_at", null: false
      t.decimal "difficulty_adjusted_ai_builder_multiple", precision: 12, scale: 4
      t.text "notes"
      t.datetime "updated_at", null: false
      t.date "week_start_date", null: false
      t.index ["week_start_date"], name: "index_github_builder_index_weeks_on_week_start_date", unique: true
    end
  end
end
