# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateModelRateOverrides < ActiveRecord::Migration[8.1]
  def change
    create_table "model_rate_overrides" do |t|
      t.decimal "cache_creation_rate", precision: 12, scale: 4
      t.decimal "cache_read_rate", precision: 12, scale: 4
      t.datetime "created_at", null: false
      t.decimal "input_rate", precision: 12, scale: 4, null: false
      t.string "model", null: false
      t.decimal "output_rate", precision: 12, scale: 4, null: false
      t.datetime "updated_at", null: false
      t.index ["model"], name: "index_model_rate_overrides_on_model", unique: true
    end
  end
end
