# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateSeasons < ActiveRecord::Migration[8.1]
  def change
    create_table "seasons" do |t|
      t.boolean "active", default: false
      t.datetime "created_at", null: false
      t.string "league", null: false
      t.string "name", null: false
      t.string "slug", null: false
      t.string "sport", null: false
      t.datetime "updated_at", null: false
      t.integer "year", null: false
      t.index ["league", "active"], name: "index_seasons_on_league_and_active"
      t.index ["slug"], name: "index_seasons_on_slug", unique: true
      t.index ["year", "league"], name: "index_seasons_on_year_and_league", unique: true
    end
  end
end
