# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateDepthCharts < ActiveRecord::Migration[8.1]
  def change
    create_table "depth_charts" do |t|
      t.datetime "created_at", null: false
      t.string "slug", null: false
      t.string "team_slug", null: false
      t.datetime "updated_at", null: false
      t.index ["slug"], name: "index_depth_charts_on_slug", unique: true
      t.index ["team_slug"], name: "index_depth_charts_on_team_slug", unique: true
    end

    add_foreign_key "depth_charts", "teams", column: "team_slug", primary_key: "slug", on_update: :cascade
  end
end
