# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateArtifacts < ActiveRecord::Migration[8.1]
  def change
    create_table "artifacts" do |t|
      t.datetime "approved_at"
      t.string "approved_by"
      t.integer "billable_units"
      t.string "brief_slug"
      t.decimal "cost_usd", precision: 10, scale: 4
      t.datetime "created_at", null: false
      t.string "generator"
      t.string "generator_endpoint"
      t.string "generator_version"
      t.string "image_url"
      t.string "kind", null: false
      t.text "prompt"
      t.datetime "retired_at"
      t.bigint "seed"
      t.string "slug", null: false
      t.string "source"
      t.datetime "updated_at", null: false
      t.index ["brief_slug"], name: "index_artifacts_on_brief_slug"
      t.index ["generator", "retired_at"], name: "index_artifacts_on_generator_and_retired_at", where: "(generator IS NOT NULL)"
      t.index ["kind", "retired_at"], name: "index_artifacts_on_kind_and_retired_at"
      t.index ["slug"], name: "index_artifacts_on_slug", unique: true
    end
  end
end
