# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateTeams < ActiveRecord::Migration[8.1]
  def change
    create_table "teams" do |t|
      t.string "coaches_url"
      t.string "color_primary"
      t.string "color_secondary"
      t.boolean "color_text_light", default: false
      t.string "conference"
      t.datetime "created_at", null: false
      t.string "division"
      t.string "emoji"
      t.string "hashtag"
      t.string "hashtag2"
      t.string "home_arena_slug"
      t.string "league"
      t.string "location"
      t.string "logo_path"
      t.string "logo_source"
      t.string "logo_url"
      t.string "mascot"
      t.string "name", null: false
      t.jsonb "rivals", default: []
      t.string "short_name"
      t.string "slug", null: false
      t.string "sport"
      t.string "team_website"
      t.datetime "updated_at", null: false
      t.string "x_handle"
      t.index ["home_arena_slug"], name: "index_teams_on_home_arena_slug"
      t.index ["slug"], name: "index_teams_on_slug", unique: true
      t.index ["sport", "league"], name: "index_teams_on_sport_and_league"
      t.index ["updated_at"], name: "index_teams_on_updated_at"
    end

    add_foreign_key "teams", "arenas", column: "home_arena_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
