# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateTaskEvents < ActiveRecord::Migration[8.1]
  def change
    create_table "task_events" do |t|
      t.string "actor"
      t.bigint "cache_creation_tokens"
      t.bigint "cache_read_tokens"
      t.decimal "cost", precision: 10, scale: 4
      t.datetime "created_at", null: false
      t.string "from_stage"
      t.string "kind", default: "transition", null: false
      t.jsonb "metadata", default: {}, null: false
      t.string "model"
      t.datetime "occurred_at", null: false
      t.integer "seconds_in_from"
      t.string "source"
      t.string "task_slug", null: false
      t.string "to_stage", null: false
      t.bigint "tokens_in"
      t.bigint "tokens_out"
      t.datetime "updated_at", null: false
      t.index ["task_slug", "kind"], name: "index_task_events_on_task_slug_and_kind"
      t.index ["task_slug", "occurred_at"], name: "index_task_events_on_task_slug_and_occurred_at"
    end

    add_foreign_key "task_events", "tasks", column: "task_slug", primary_key: "slug", on_update: :cascade
  end
end
