# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateDevopsShifts < ActiveRecord::Migration[8.1]
  def change
    create_table "devops_shifts" do |t|
      t.datetime "acquired_at"
      t.datetime "claim_expires_at"
      t.string "claim_nonce"
      t.string "claimed_session"
      t.datetime "created_at", null: false
      t.string "holder_label"
      t.string "lane", null: false
      t.datetime "updated_at", null: false
      t.index ["lane"], name: "index_devops_shifts_on_lane", unique: true
    end
  end
end
