# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateKnowledgeSources < ActiveRecord::Migration[8.1]
  def change
    create_table "knowledge_sources" do |t|
      t.jsonb "access", default: {}, null: false
      t.datetime "created_at", null: false
      t.boolean "enabled", default: true, null: false
      t.string "entity"
      t.string "external_root_id", null: false
      t.string "kind", null: false
      t.string "last_walk_error"
      t.datetime "last_walked_at"
      t.string "name", null: false
      t.datetime "updated_at", null: false
      t.bigint "workspace_account_id"
      t.index ["kind", "external_root_id"], name: "index_knowledge_sources_on_kind_and_external_root_id", unique: true
      t.index ["workspace_account_id"], name: "index_knowledge_sources_on_workspace_account_id"
    end

    add_foreign_key "knowledge_sources", "workspace_accounts"
  end
end
