# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateSlates < ActiveRecord::Migration[8.1]
  def change
    create_table "slates" do |t|
      t.datetime "created_at", null: false
      t.date "ends_at"
      t.string "label", null: false
      t.string "season_slug", null: false
      t.integer "sequence", null: false
      t.string "slate_type", null: false
      t.string "slug", null: false
      t.date "starts_at"
      t.datetime "updated_at", null: false
      t.index ["season_slug", "sequence"], name: "index_slates_on_season_slug_and_sequence", unique: true
      t.index ["season_slug"], name: "index_slates_on_season_slug"
      t.index ["slug"], name: "index_slates_on_slug", unique: true
    end

    add_foreign_key "slates", "seasons", column: "season_slug", primary_key: "slug", on_update: :cascade
  end
end
