# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateVideoPerformers < ActiveRecord::Migration[8.1]
  def change
    create_table "video_performers" do |t|
      t.string "artist_slug"
      t.text "confidence_note"
      t.datetime "created_at", null: false
      t.boolean "extra", default: false, null: false
      t.string "label", null: false
      t.string "music_video_slug", null: false
      t.integer "ordinal", null: false
      t.string "recast_appearance_slug"
      t.boolean "recast_keep", default: false, null: false
      t.string "recast_person_slug"
      t.jsonb "sightings", default: [], null: false
      t.jsonb "still_object_keys", default: [], null: false
      t.datetime "updated_at", null: false
      t.index ["artist_slug"], name: "index_video_performers_on_artist_slug"
      t.index ["music_video_slug", "ordinal"], name: "index_video_performers_on_music_video_slug_and_ordinal", unique: true
      t.index ["recast_appearance_slug"], name: "index_video_performers_on_recast_appearance_slug"
      t.index ["recast_person_slug"], name: "index_video_performers_on_recast_person_slug"
    end

    add_foreign_key "video_performers", "appearances", column: "recast_appearance_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
    add_foreign_key "video_performers", "artists", column: "artist_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
    add_foreign_key "video_performers", "music_videos", column: "music_video_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "video_performers", "people", column: "recast_person_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
