# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateTasks < ActiveRecord::Migration[8.1]
  def change
    create_table "tasks" do |t|
      t.string "actual_size"
      t.string "agent_slug"
      t.string "approval_status"
      t.datetime "archived_at"
      t.datetime "assembled_at"
      t.string "block_kind"
      t.datetime "blocked_at"
      t.string "blocked_by"
      t.string "blocked_from"
      t.string "branch"
      t.datetime "completed_at"
      t.datetime "created_at", null: false
      t.jsonb "dependencies", default: [], null: false
      t.text "description"
      t.string "dev_size"
      t.string "epic_slug"
      t.text "error_message"
      t.datetime "failed_at"
      t.datetime "g1_failed_at"
      t.datetime "g1_testing_finished_at"
      t.datetime "g1_testing_started_at"
      t.jsonb "gates", default: {}, null: false
      t.datetime "gates_cached_at"
      t.integer "gates_version", default: 0, null: false
      t.string "merged"
      t.jsonb "metadata", default: {}
      t.string "pm_size"
      t.string "po_size"
      t.integer "position"
      t.string "pr_url"
      t.integer "priority", default: 0
      t.datetime "queued_at"
      t.string "release_slug"
      t.jsonb "required_skills", default: []
      t.boolean "requires_migration", default: false, null: false
      t.jsonb "result", default: {}
      t.datetime "reviewed_at"
      t.string "session_id"
      t.datetime "sizes_revealed_at"
      t.string "slug", null: false
      t.string "stage", default: "designed"
      t.datetime "started_at"
      t.datetime "submitted_at"
      t.jsonb "testing_phases", default: {}, null: false
      t.datetime "testing_phases_cached_at"
      t.integer "testing_phases_version", default: 0, null: false
      t.string "title", null: false
      t.datetime "updated_at", null: false
      t.index ["agent_slug"], name: "index_tasks_on_agent_slug"
      t.index ["approval_status"], name: "index_tasks_on_approval_status"
      t.index ["branch"], name: "index_tasks_on_branch"
      t.index ["epic_slug"], name: "index_tasks_on_epic_slug"
      t.index ["pr_url"], name: "index_tasks_on_pr_url"
      t.index ["priority"], name: "index_tasks_on_priority"
      t.index ["release_slug"], name: "index_tasks_on_release_slug"
      t.index ["requires_migration"], name: "index_tasks_on_requires_migration"
      t.index ["session_id"], name: "index_tasks_on_session_id"
      t.index ["slug"], name: "index_tasks_on_slug", unique: true
      t.index ["stage", "created_at"], name: "index_tasks_on_stage_and_created_at"
      t.index ["stage", "position"], name: "index_tasks_on_stage_and_position"
      t.index ["stage"], name: "index_tasks_on_stage"
    end

    add_foreign_key "tasks", "agents", column: "agent_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
    add_foreign_key "tasks", "releases", column: "release_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
