# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateBroadcasts < ActiveRecord::Migration[8.1]
  def change
    create_table "broadcasts" do |t|
      t.datetime "created_at", null: false
      t.string "header"
      t.string "hero_url"
      t.string "preview_text"
      t.datetime "sent_at"
      t.string "slug", null: false
      t.string "status", default: "draft", null: false
      t.string "subheader"
      t.string "subject", default: "", null: false
      t.string "survivor_url"
      t.string "target_list"
      t.string "template_key", null: false
      t.string "turf_totals_url"
      t.datetime "updated_at", null: false
      t.index ["slug"], name: "index_broadcasts_on_slug", unique: true
      t.index ["status"], name: "index_broadcasts_on_status"
    end
  end
end
