# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateImportRuns < ActiveRecord::Migration[8.1]
  def change
    create_table "import_runs" do |t|
      t.datetime "created_at", null: false
      t.text "detail"
      t.datetime "finished_at"
      t.integer "rows_changed", default: 0
      t.integer "rows_seen", default: 0
      t.string "source", null: false
      t.datetime "started_at", null: false
      t.jsonb "stats", default: {}, null: false
      t.string "status", default: "running", null: false
      t.datetime "updated_at", null: false
      t.index ["source", "started_at"], name: "index_import_runs_on_source_and_started_at"
    end
  end
end
