# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreatePersonJewelries < ActiveRecord::Migration[8.1]
  def change
    create_table "person_jewelries" do |t|
      t.datetime "created_at", null: false
      t.text "description", null: false
      t.string "image_url"
      t.string "kind", null: false
      t.string "name", null: false
      t.string "person_slug", null: false
      t.string "slug", null: false
      t.string "source"
      t.datetime "updated_at", null: false
      t.integer "year"
      t.index ["person_slug", "kind"], name: "index_person_jewelries_on_person_slug_and_kind"
      t.index ["slug"], name: "index_person_jewelries_on_slug", unique: true
    end

    add_foreign_key "person_jewelries", "people", column: "person_slug", primary_key: "slug", on_update: :cascade
  end
end
