# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateDeskSnapshots < ActiveRecord::Migration[8.1]
  def change
    create_table "desk_snapshots" do |t|
      t.jsonb "capacity", default: {}, null: false
      t.datetime "created_at", null: false
      t.integer "desk_count", default: 0, null: false
      t.datetime "generated_at", null: false
      t.string "hub_dir"
      t.string "projects_dir"
      t.jsonb "redis_db_range", default: {}, null: false
      t.jsonb "summary", default: {}, null: false
      t.datetime "updated_at", null: false
      t.index ["generated_at"], name: "index_desk_snapshots_on_generated_at"
    end
  end
end
