# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class EnableExtensions < ActiveRecord::Migration[8.1]
  def change
    enable_extension "pg_catalog.plpgsql"
  end
end
