# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateContracts < ActiveRecord::Migration[8.1]
  def change
    create_table "contracts" do |t|
      t.bigint "annual_value_cents"
      t.string "contract_type", default: "active"
      t.datetime "created_at", null: false
      t.date "expires_at"
      t.string "person_slug", null: false
      t.string "position"
      t.string "slug", null: false
      t.string "team_slug", null: false
      t.datetime "updated_at", null: false
      t.index ["contract_type"], name: "index_contracts_on_contract_type"
      t.index ["expires_at"], name: "index_contracts_on_expires_at"
      t.index ["person_slug", "team_slug"], name: "index_contracts_on_person_slug_and_team_slug", unique: true
      t.index ["person_slug"], name: "index_contracts_on_person_slug"
      t.index ["slug"], name: "index_contracts_on_slug", unique: true
      t.index ["team_slug"], name: "index_contracts_on_team_slug"
    end

    add_foreign_key "contracts", "people", column: "person_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "contracts", "teams", column: "team_slug", primary_key: "slug", on_update: :cascade
  end
end
