# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateMusicVideos < ActiveRecord::Migration[8.1]
  def change
    create_table "music_videos" do |t|
      t.jsonb "caption_timing", default: {"cues"=>[], "sections"=>[]}, null: false
      t.integer "chunk_ms"
      t.integer "chunk_overlap_ms"
      t.datetime "created_at", null: false
      t.integer "duration_ms"
      t.string "info_object_key"
      t.string "kind", default: "music_video", null: false
      t.string "platform", null: false
      t.string "slug", null: false
      t.string "source_id", null: false
      t.string "source_object_key", null: false
      t.string "source_url", null: false
      t.string "stage", default: "digested", null: false
      t.string "title", null: false
      t.jsonb "unresolved_credits", default: [], null: false
      t.datetime "updated_at", null: false
      t.index ["platform", "source_id"], name: "index_music_videos_on_platform_and_source_id", unique: true
      t.index ["slug"], name: "index_music_videos_on_slug", unique: true
    end
  end
end
