# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreatePeople < ActiveRecord::Migration[8.1]
  def change
    create_table "people" do |t|
      t.jsonb "aliases", default: []
      t.boolean "athlete", default: false
      t.string "avatar_url"
      t.boolean "coach", default: false
      t.datetime "created_at", null: false
      t.string "default_appearance_slug"
      t.string "disambiguator"
      t.string "email"
      t.string "facebook_url"
      t.string "first_name", null: false
      t.string "instagram_url"
      t.string "last_name", null: false
      t.string "linkedin_url"
      t.string "location"
      t.string "primary_vocation"
      t.string "slug", null: false
      t.datetime "updated_at", null: false
      t.jsonb "vocations", default: [], null: false
      t.string "website_url"
      t.string "x_url"
      t.index ["default_appearance_slug"], name: "index_people_on_default_appearance_slug"
      t.index ["email"], name: "index_people_on_email"
      t.index ["last_name", "first_name"], name: "index_people_on_last_name_and_first_name"
      t.index ["primary_vocation"], name: "index_people_on_primary_vocation"
      t.index ["slug"], name: "index_people_on_slug", unique: true
      t.index ["updated_at"], name: "index_people_on_updated_at"
    end
  end
end
