# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateAltVideoClips < ActiveRecord::Migration[8.1]
  def change
    create_table "alt_video_clips" do |t|
      t.string "alt_video_slug", null: false
      t.integer "chunk_ordinal", null: false
      t.datetime "created_at", null: false
      t.integer "end_ms", null: false
      t.string "regenerate_note"
      t.datetime "regenerate_requested_at"
      t.string "slug", null: false
      t.integer "start_ms", null: false
      t.datetime "updated_at", null: false
      t.index ["alt_video_slug", "chunk_ordinal"], name: "index_alt_video_clips_on_alt_video_slug_and_chunk_ordinal", unique: true
      t.index ["slug"], name: "index_alt_video_clips_on_slug", unique: true
    end

    add_foreign_key "alt_video_clips", "alt_videos", column: "alt_video_slug", primary_key: "slug", on_update: :cascade
  end
end
