# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateUsers < ActiveRecord::Migration[8.1]
  def change
    create_table "users" do |t|
      t.integer "birth_day"
      t.integer "birth_month"
      t.integer "birth_year"
      t.datetime "created_at", null: false
      t.string "email"
      t.datetime "email_verified_at"
      t.string "first_name"
      t.jsonb "ip_locations", default: [], null: false
      t.datetime "joined_email_list_at"
      t.string "last_name"
      t.datetime "left_email_list_at"
      t.string "name"
      t.string "password_digest"
      t.string "provider"
      t.string "role", default: "viewer"
      t.string "session_token"
      t.string "slug"
      t.string "uid"
      t.datetime "updated_at", null: false
      t.index ["email"], name: "index_users_on_email", unique: true
      t.index ["slug"], name: "index_users_on_slug", unique: true
    end
  end
end
