# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateTiktokDrafts < ActiveRecord::Migration[8.1]
  def change
    create_table "tiktok_drafts" do |t|
      t.bigint "byte_size"
      t.text "caption", null: false
      t.integer "chunk_count"
      t.string "clip_slug", null: false
      t.datetime "created_at", null: false
      t.text "error"
      t.jsonb "facts", default: {}, null: false
      t.string "fail_reason"
      t.datetime "finished_at"
      t.datetime "polled_at"
      t.string "publish_id"
      t.string "requested_by"
      t.string "state", default: "queued", null: false
      t.string "tiktok_status"
      t.datetime "updated_at", null: false
      t.datetime "uploaded_at"
      t.integer "version_number", null: false
      t.string "version_object_key", null: false
      t.index ["clip_slug", "created_at"], name: "index_tiktok_drafts_on_clip_slug_and_created_at"
      t.index ["publish_id"], name: "index_tiktok_drafts_on_publish_id", unique: true, where: "(publish_id IS NOT NULL)"
      t.index ["state"], name: "index_tiktok_drafts_on_state"
    end

    add_foreign_key "tiktok_drafts", "alt_video_clips", column: "clip_slug", primary_key: "slug", on_update: :cascade
  end
end
