# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateRosters < ActiveRecord::Migration[8.1]
  def change
    create_table "rosters" do |t|
      t.datetime "created_at", null: false
      t.string "slate_slug", null: false
      t.string "slug", null: false
      t.string "team_slug", null: false
      t.datetime "updated_at", null: false
      t.index ["slate_slug"], name: "index_rosters_on_slate_slug"
      t.index ["slug"], name: "index_rosters_on_slug", unique: true
      t.index ["team_slug", "slate_slug"], name: "index_rosters_on_team_slug_and_slate_slug", unique: true
      t.index ["team_slug"], name: "index_rosters_on_team_slug"
    end

    add_foreign_key "rosters", "slates", column: "slate_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "rosters", "teams", column: "team_slug", primary_key: "slug", on_update: :cascade
  end
end
