# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateContents < ActiveRecord::Migration[8.1]
  def change
    create_table "contents" do |t|
      t.datetime "artifacts_approved_at"
      t.datetime "assembled_at"
      t.datetime "asset_at"
      t.jsonb "caption_variants", default: []
      t.text "captions"
      t.string "claim_session"
      t.datetime "claimed_at"
      t.string "claimed_by"
      t.string "colorway"
      t.integer "comments_count"
      t.string "content_type", default: "tiktok_video"
      t.datetime "created_at", null: false
      t.text "description"
      t.integer "duration_seconds"
      t.string "final_video_url"
      t.jsonb "game_facts", default: {}, null: false
      t.string "game_slug"
      t.jsonb "hashtags", default: []
      t.jsonb "hook_ideas", default: []
      t.string "hook_image_url"
      t.datetime "hooked_at"
      t.integer "likes"
      t.boolean "logo_overlay", default: true
      t.jsonb "music_suggestions", default: []
      t.string "music_track"
      t.string "platform", default: "tiktok"
      t.integer "position"
      t.string "post_id"
      t.string "post_url"
      t.datetime "posted_at"
      t.string "qb_player_slug"
      t.integer "reference_video_end"
      t.integer "reference_video_start"
      t.string "reference_video_url"
      t.text "review_notes"
      t.datetime "reviewed_at"
      t.string "rival_team_slug"
      t.jsonb "scene_assets", default: []
      t.jsonb "scenes", default: []
      t.text "script_text"
      t.datetime "scripted_at"
      t.integer "selected_hook_index"
      t.integer "shares"
      t.string "skill_player_slug"
      t.string "slug", null: false
      t.string "source_news_slug"
      t.string "source_type"
      t.string "stage", default: "idea", null: false
      t.string "team_slug"
      t.jsonb "text_overlays", default: []
      t.string "title", null: false
      t.datetime "updated_at", null: false
      t.integer "views"
      t.string "workflow", default: "video", null: false
      t.index ["game_slug", "workflow"], name: "index_contents_on_game_slug_and_workflow_when_present", unique: true, where: "(game_slug IS NOT NULL)"
      t.index ["rival_team_slug"], name: "index_contents_on_rival_team_slug"
      t.index ["slug"], name: "index_contents_on_slug", unique: true
      t.index ["source_news_slug"], name: "index_contents_on_source_news_slug"
      t.index ["stage", "claimed_at"], name: "index_contents_on_stage_and_claimed_at"
      t.index ["stage", "position"], name: "index_contents_on_stage_and_position"
      t.index ["stage"], name: "index_contents_on_stage"
      t.index ["team_slug"], name: "index_contents_on_team_slug"
      t.index ["workflow"], name: "index_contents_on_workflow"
    end

    add_foreign_key "contents", "news", column: "source_news_slug", primary_key: "slug", on_update: :cascade, on_delete: :nullify
  end
end
