# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateSourceDocuments < ActiveRecord::Migration[8.1]
  def change
    create_table "source_documents" do |t|
      t.jsonb "access", default: {}, null: false
      t.bigint "byte_size"
      t.string "checksum"
      t.datetime "created_at", null: false
      t.string "entity"
      t.string "external_id", null: false
      t.string "indexed_version"
      t.bigint "knowledge_source_id", null: false
      t.datetime "last_indexed_at"
      t.datetime "last_seen_at"
      t.jsonb "metadata", default: {}, null: false
      t.string "mime_type"
      t.string "owner_email"
      t.jsonb "parents", default: [], null: false
      t.datetime "remote_modified_at"
      t.string "remote_version"
      t.string "status", default: "active", null: false
      t.jsonb "tags", default: [], null: false
      t.string "title"
      t.datetime "updated_at", null: false
      t.string "web_url"
      t.index ["knowledge_source_id", "external_id"], name: "index_source_documents_on_knowledge_source_id_and_external_id", unique: true
      t.index ["knowledge_source_id", "status"], name: "index_source_documents_on_knowledge_source_id_and_status"
      t.index ["knowledge_source_id"], name: "index_source_documents_on_knowledge_source_id"
    end

    add_foreign_key "source_documents", "knowledge_sources"
  end
end
