# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateCredentialRecords < ActiveRecord::Migration[8.1]
  def change
    create_table "credential_records" do |t|
      t.string "category"
      t.datetime "created_at", null: false
      t.string "credential_vault_slug", null: false
      t.string "entity"
      t.text "notes"
      t.text "scope_summary"
      t.string "service", null: false
      t.string "status", default: "filed", null: false
      t.string "title", null: false
      t.datetime "updated_at", null: false
      t.string "url"
      t.string "used_by"
      t.index ["credential_vault_slug", "title"], name: "index_credential_records_on_credential_vault_slug_and_title", unique: true
      t.index ["service"], name: "index_credential_records_on_service"
      t.index ["status"], name: "index_credential_records_on_status"
    end

    add_foreign_key "credential_records", "credential_vaults", column: "credential_vault_slug", primary_key: "slug", on_update: :cascade
  end
end
