# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateDepthChartEntries < ActiveRecord::Migration[8.1]
  def change
    create_table "depth_chart_entries" do |t|
      t.datetime "created_at", null: false
      t.integer "depth", null: false
      t.string "depth_chart_slug", null: false
      t.string "formation_slot"
      t.boolean "locked", default: false, null: false
      t.string "person_slug", null: false
      t.string "position", null: false
      t.string "side", null: false
      t.datetime "updated_at", null: false
      t.index ["depth_chart_slug", "person_slug", "position"], name: "idx_dce_unique", unique: true
      t.index ["depth_chart_slug", "position", "depth"], name: "idx_on_depth_chart_slug_position_depth_8e80d39ff6"
      t.index ["depth_chart_slug"], name: "index_depth_chart_entries_on_depth_chart_slug"
      t.index ["formation_slot"], name: "index_depth_chart_entries_on_formation_slot"
    end

    add_foreign_key "depth_chart_entries", "depth_charts", column: "depth_chart_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "depth_chart_entries", "people", column: "person_slug", primary_key: "slug", on_update: :cascade
  end
end
