# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateCoachRankings < ActiveRecord::Migration[8.1]
  def change
    create_table "coach_rankings" do |t|
      t.string "coach_slug", null: false
      t.datetime "created_at", null: false
      t.integer "rank", null: false
      t.string "rank_type", null: false
      t.string "season_slug", null: false
      t.string "slug", null: false
      t.string "tier"
      t.datetime "updated_at", null: false
      t.index ["coach_slug", "rank_type", "season_slug"], name: "index_coach_rankings_unique_type_season", unique: true
      t.index ["coach_slug"], name: "index_coach_rankings_on_coach_slug"
      t.index ["season_slug"], name: "index_coach_rankings_on_season_slug"
      t.index ["slug"], name: "index_coach_rankings_on_slug", unique: true
    end

    add_foreign_key "coach_rankings", "coaches", column: "coach_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "coach_rankings", "seasons", column: "season_slug", primary_key: "slug", on_update: :cascade
  end
end
