# Generated by bin/db-baseline from the schema. Change the schema with a new migration, never here.
class CreateGames < ActiveRecord::Migration[8.1]
  def change
    create_table "games" do |t|
      t.string "away_team_slug", null: false
      t.datetime "created_at", null: false
      t.string "home_team_slug", null: false
      t.datetime "kickoff_at"
      t.string "location"
      t.string "slate_slug", null: false
      t.string "slug", null: false
      t.string "status", default: "scheduled"
      t.datetime "updated_at", null: false
      t.string "venue"
      t.index ["away_team_slug"], name: "index_games_on_away_team_slug"
      t.index ["home_team_slug"], name: "index_games_on_home_team_slug"
      t.index ["slate_slug"], name: "index_games_on_slate_slug"
      t.index ["slug"], name: "index_games_on_slug", unique: true
    end

    add_foreign_key "games", "slates", column: "slate_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "games", "teams", column: "away_team_slug", primary_key: "slug", on_update: :cascade
    add_foreign_key "games", "teams", column: "home_team_slug", primary_key: "slug", on_update: :cascade
  end
end
